// <auto-generated />
#nullable enable
class AccessTextConverter :
    WriteOnlyJsonConverter<AccessText>
{
    public override void Write(VerifyJsonWriter writer, AccessText value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TextBlockConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, AccessText value)
    {
        var type = typeof(AccessText);
        writer.WriteMember(value, value.AccessKey, "AccessKey");
        if (AccessText.ShowAccessKeyProperty.ShouldIncludeProperty(value, value.ShowAccessKey))
        {
            writer.WriteMember(value, value.ShowAccessKey, "ShowAccessKey");
        }
    }
}
