// <auto-generated />
#nullable enable
class AdornerLayerConverter :
    WriteOnlyJsonConverter<AdornerLayer>,
    IAvaloniaConverter<AdornerLayer>
{
    public override void Write(VerifyJsonWriter writer, AdornerLayer value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        CanvasConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, AdornerLayer value)
    {
        if (!object.Equals(AdornerLayer.DefaultFocusAdornerProperty.GetDefaultValue(typeof(AdornerLayer)), value.DefaultFocusAdorner))
        {
            writer.WriteMember(value, value.DefaultFocusAdorner, "DefaultFocusAdorner");
        }
    }

    public static bool MemberHasValue(AdornerLayer target, string member, object? value)
    {
        if (member == "DefaultFocusAdorner")
        {
            return object.Equals(target.DefaultFocusAdorner, value);
        }
        CanvasConverter.MemberHasValue(target, member, value);
        throw new($"Member not found: {member}");
    }
}
