// <auto-generated />
#nullable enable
class ArcConverter :
    WriteOnlyJsonConverter<Arc>
{
    public override void Write(VerifyJsonWriter writer, Arc value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ShapeConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Arc value)
    {
        var type = typeof(Arc);
        if (value.ShouldIncludeProperty(Arc.StartAngleProperty))
        if (!object.Equals(Arc.StartAngleProperty.GetDefaultValue(type), value.StartAngle))
        {
            writer.WriteMember(value, value.StartAngle, "StartAngle");
        }
        if (value.ShouldIncludeProperty(Arc.SweepAngleProperty))
        if (!object.Equals(Arc.SweepAngleProperty.GetDefaultValue(type), value.SweepAngle))
        {
            writer.WriteMember(value, value.SweepAngle, "SweepAngle");
        }
    }
}
