// <auto-generated />
#nullable enable
class AutoCompleteBoxConverter :
    WriteOnlyJsonConverter<AutoCompleteBox>,
    IAvaloniaConverter<AutoCompleteBox>
{
    public override void Write(VerifyJsonWriter writer, AutoCompleteBox value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TemplatedControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, AutoCompleteBox value)
    {
        if (!object.Equals(AutoCompleteBox.MinimumPrefixLengthProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.MinimumPrefixLength))
        {
            writer.WriteMember(value, value.MinimumPrefixLength, "MinimumPrefixLength");
        }
        if (!object.Equals(AutoCompleteBox.IsTextCompletionEnabledProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.IsTextCompletionEnabled))
        {
            writer.WriteMember(value, value.IsTextCompletionEnabled, "IsTextCompletionEnabled");
        }
        if (!object.Equals(AutoCompleteBox.ItemTemplateProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.ItemTemplate))
        {
            writer.WriteMember(value, value.ItemTemplate, "ItemTemplate");
        }
        if (!object.Equals(AutoCompleteBox.MinimumPopulateDelayProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.MinimumPopulateDelay))
        {
            writer.WriteMember(value, value.MinimumPopulateDelay, "MinimumPopulateDelay");
        }
        if (!object.Equals(AutoCompleteBox.MaxDropDownHeightProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.MaxDropDownHeight))
        {
            writer.WriteMember(value, value.MaxDropDownHeight, "MaxDropDownHeight");
        }
        if (!object.Equals(AutoCompleteBox.IsDropDownOpenProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.IsDropDownOpen))
        {
            writer.WriteMember(value, value.IsDropDownOpen, "IsDropDownOpen");
        }
        writer.WriteMember(value, value.ValueMemberBinding, "ValueMemberBinding");
        if (!object.Equals(AutoCompleteBox.SelectedItemProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.SelectedItem))
        {
            writer.WriteMember(value, value.SelectedItem, "SelectedItem");
        }
        if (!object.Equals(AutoCompleteBox.TextProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.Text))
        {
            writer.WriteMember(value, value.Text, "Text");
        }
        if (!object.Equals(AutoCompleteBox.SearchTextProperty.GetUnsetValue(typeof(AutoCompleteBox)), value.SearchText))
        {
            writer.WriteMember(value, value.SearchText, "SearchText");
        }
        if (!object.Equals(AutoCompleteBox.FilterModeProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.FilterMode))
        {
            writer.WriteMember(value, value.FilterMode, "FilterMode");
        }
        if (!object.Equals(AutoCompleteBox.WatermarkProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.Watermark))
        {
            writer.WriteMember(value, value.Watermark, "Watermark");
        }
        if (!object.Equals(AutoCompleteBox.ItemFilterProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.ItemFilter))
        {
            writer.WriteMember(value, value.ItemFilter, "ItemFilter");
        }
        if (!object.Equals(AutoCompleteBox.TextFilterProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.TextFilter))
        {
            writer.WriteMember(value, value.TextFilter, "TextFilter");
        }
        if (!object.Equals(AutoCompleteBox.ItemSelectorProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.ItemSelector))
        {
            writer.WriteMember(value, value.ItemSelector, "ItemSelector");
        }
        if (!object.Equals(AutoCompleteBox.TextSelectorProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.TextSelector))
        {
            writer.WriteMember(value, value.TextSelector, "TextSelector");
        }
        if (!object.Equals(AutoCompleteBox.AsyncPopulatorProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.AsyncPopulator))
        {
            writer.WriteMember(value, value.AsyncPopulator, "AsyncPopulator");
        }
        if (!object.Equals(AutoCompleteBox.ItemsSourceProperty.GetDefaultValue(typeof(AutoCompleteBox)), value.ItemsSource))
        {
            writer.WriteMember(value, value.ItemsSource, "ItemsSource");
        }
    }

    public static bool MemberHasValue(AutoCompleteBox target, string member, object? value)
    {
        if (member == "MinimumPrefixLength")
        {
            return object.Equals(target.MinimumPrefixLength, value);
        }
        if (member == "IsTextCompletionEnabled")
        {
            return object.Equals(target.IsTextCompletionEnabled, value);
        }
        if (member == "ItemTemplate")
        {
            return object.Equals(target.ItemTemplate, value);
        }
        if (member == "MinimumPopulateDelay")
        {
            return object.Equals(target.MinimumPopulateDelay, value);
        }
        if (member == "MaxDropDownHeight")
        {
            return object.Equals(target.MaxDropDownHeight, value);
        }
        if (member == "IsDropDownOpen")
        {
            return object.Equals(target.IsDropDownOpen, value);
        }
        if (member == "ValueMemberBinding")
        {
            return object.Equals(target.ValueMemberBinding, value);
        }
        if (member == "SelectedItem")
        {
            return object.Equals(target.SelectedItem, value);
        }
        if (member == "Text")
        {
            return object.Equals(target.Text, value);
        }
        if (member == "SearchText")
        {
            return object.Equals(target.SearchText, value);
        }
        if (member == "FilterMode")
        {
            return object.Equals(target.FilterMode, value);
        }
        if (member == "Watermark")
        {
            return object.Equals(target.Watermark, value);
        }
        if (member == "ItemFilter")
        {
            return object.Equals(target.ItemFilter, value);
        }
        if (member == "TextFilter")
        {
            return object.Equals(target.TextFilter, value);
        }
        if (member == "ItemSelector")
        {
            return object.Equals(target.ItemSelector, value);
        }
        if (member == "TextSelector")
        {
            return object.Equals(target.TextSelector, value);
        }
        if (member == "AsyncPopulator")
        {
            return object.Equals(target.AsyncPopulator, value);
        }
        if (member == "ItemsSource")
        {
            return object.Equals(target.ItemsSource, value);
        }
        TemplatedControlConverter.MemberHasValue(target, member, value);
        throw new($"Member not found: {member}");
    }
}
