// <auto-generated />
class ButtonSpinnerConverter :
    WriteOnlyJsonConverter<ButtonSpinner>
{
    public override void Write(VerifyJsonWriter writer, ButtonSpinner value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        SpinnerConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ButtonSpinner value)
    {
        if (!ButtonSpinner.AllowSpinProperty.GetDefaultValue(typeof(ButtonSpinner)).Equals(value.AllowSpin))
        {
            writer.WriteMember(value, value.AllowSpin, "AllowSpin");
        }
        if (!ButtonSpinner.ShowButtonSpinnerProperty.GetDefaultValue(typeof(ButtonSpinner)).Equals(value.ShowButtonSpinner))
        {
            writer.WriteMember(value, value.ShowButtonSpinner, "ShowButtonSpinner");
        }
        if (!ButtonSpinner.ButtonSpinnerLocationProperty.GetDefaultValue(typeof(ButtonSpinner)).Equals(value.ButtonSpinnerLocation))
        {
            writer.WriteMember(value, value.ButtonSpinnerLocation, "ButtonSpinnerLocation");
        }
    }
}
