// <auto-generated />
#nullable enable
class ButtonSpinnerConverter :
    WriteOnlyJsonConverter<ButtonSpinner>
{
    public override void Write(VerifyJsonWriter writer, ButtonSpinner value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        SpinnerConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ButtonSpinner value)
    {
        var type = typeof(ButtonSpinner);
        if (ButtonSpinner.AllowSpinProperty.ShouldIncludeProperty(value, value.AllowSpin))
        {
            writer.WriteMember(value, value.AllowSpin, "AllowSpin");
        }
        if (ButtonSpinner.ShowButtonSpinnerProperty.ShouldIncludeProperty(value, value.ShowButtonSpinner))
        {
            writer.WriteMember(value, value.ShowButtonSpinner, "ShowButtonSpinner");
        }
        if (ButtonSpinner.ButtonSpinnerLocationProperty.ShouldIncludeProperty(value, value.ButtonSpinnerLocation))
        {
            writer.WriteMember(value, value.ButtonSpinnerLocation, "ButtonSpinnerLocation");
        }
    }
}
