// <auto-generated />
#nullable enable
class CalendarItemConverter :
    WriteOnlyJsonConverter<CalendarItem>
{
    public override void Write(VerifyJsonWriter writer, CalendarItem value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TemplatedControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, CalendarItem value)
    {
        var type = typeof(CalendarItem);
        if (value.ShouldIncludeProperty(CalendarItem.HeaderBackgroundProperty))
        if (!object.Equals(CalendarItem.HeaderBackgroundProperty.GetDefaultValue(type), value.HeaderBackground))
        {
            writer.WriteMember(value, value.HeaderBackground, "HeaderBackground");
        }
        if (value.ShouldIncludeProperty(CalendarItem.DayTitleTemplateProperty))
        if (!object.Equals(CalendarItem.DayTitleTemplateProperty.GetDefaultValue(type), value.DayTitleTemplate))
        {
            writer.WriteMember(value, value.DayTitleTemplate, "DayTitleTemplate");
        }
    }
}
