// <auto-generated />
#nullable enable
class CalendarDatePickerConverter :
    WriteOnlyJsonConverter<CalendarDatePicker>
{
    public override void Write(VerifyJsonWriter writer, CalendarDatePicker value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TemplatedControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, CalendarDatePicker value)
    {
         writer.WriteMember(value, value.BlackoutDates, "BlackoutDates");
        if (!object.Equals(CalendarDatePicker.DisplayDateProperty.GetDefaultValue(typeof(CalendarDatePicker)), value.DisplayDate))
        {
            writer.WriteMember(value, value.DisplayDate, "DisplayDate");
        }
        if (!object.Equals(CalendarDatePicker.DisplayDateStartProperty.GetDefaultValue(typeof(CalendarDatePicker)), value.DisplayDateStart))
        {
            writer.WriteMember(value, value.DisplayDateStart, "DisplayDateStart");
        }
        if (!object.Equals(CalendarDatePicker.DisplayDateEndProperty.GetDefaultValue(typeof(CalendarDatePicker)), value.DisplayDateEnd))
        {
            writer.WriteMember(value, value.DisplayDateEnd, "DisplayDateEnd");
        }
        if (!object.Equals(CalendarDatePicker.FirstDayOfWeekProperty.GetDefaultValue(typeof(CalendarDatePicker)), value.FirstDayOfWeek))
        {
            writer.WriteMember(value, value.FirstDayOfWeek, "FirstDayOfWeek");
        }
        if (!object.Equals(CalendarDatePicker.IsDropDownOpenProperty.GetDefaultValue(typeof(CalendarDatePicker)), value.IsDropDownOpen))
        {
            writer.WriteMember(value, value.IsDropDownOpen, "IsDropDownOpen");
        }
        if (!object.Equals(CalendarDatePicker.IsTodayHighlightedProperty.GetDefaultValue(typeof(CalendarDatePicker)), value.IsTodayHighlighted))
        {
            writer.WriteMember(value, value.IsTodayHighlighted, "IsTodayHighlighted");
        }
        if (!object.Equals(CalendarDatePicker.SelectedDateProperty.GetDefaultValue(typeof(CalendarDatePicker)), value.SelectedDate))
        {
            writer.WriteMember(value, value.SelectedDate, "SelectedDate");
        }
        if (!object.Equals(CalendarDatePicker.SelectedDateFormatProperty.GetDefaultValue(typeof(CalendarDatePicker)), value.SelectedDateFormat))
        {
            writer.WriteMember(value, value.SelectedDateFormat, "SelectedDateFormat");
        }
        if (!object.Equals(CalendarDatePicker.CustomDateFormatStringProperty.GetDefaultValue(typeof(CalendarDatePicker)), value.CustomDateFormatString))
        {
            writer.WriteMember(value, value.CustomDateFormatString, "CustomDateFormatString");
        }
        if (!object.Equals(CalendarDatePicker.TextProperty.GetDefaultValue(typeof(CalendarDatePicker)), value.Text))
        {
            writer.WriteMember(value, value.Text, "Text");
        }
        if (!object.Equals(CalendarDatePicker.WatermarkProperty.GetDefaultValue(typeof(CalendarDatePicker)), value.Watermark))
        {
            writer.WriteMember(value, value.Watermark, "Watermark");
        }
        if (!object.Equals(CalendarDatePicker.UseFloatingWatermarkProperty.GetDefaultValue(typeof(CalendarDatePicker)), value.UseFloatingWatermark))
        {
            writer.WriteMember(value, value.UseFloatingWatermark, "UseFloatingWatermark");
        }
        if (!object.Equals(CalendarDatePicker.HorizontalContentAlignmentProperty.GetDefaultValue(typeof(CalendarDatePicker)), value.HorizontalContentAlignment))
        {
            writer.WriteMember(value, value.HorizontalContentAlignment, "HorizontalContentAlignment");
        }
        if (!object.Equals(CalendarDatePicker.VerticalContentAlignmentProperty.GetDefaultValue(typeof(CalendarDatePicker)), value.VerticalContentAlignment))
        {
            writer.WriteMember(value, value.VerticalContentAlignment, "VerticalContentAlignment");
        }
    }

    public static bool MemberHasValue(CalendarDatePicker target, string member, object? value)
    {
        if (member == "BlackoutDates")
        {
            return object.Equals(target.BlackoutDates, value);
        }
        if (member == "DisplayDate")
        {
            return object.Equals(target.DisplayDate, value);
        }
        if (member == "DisplayDateStart")
        {
            return object.Equals(target.DisplayDateStart, value);
        }
        if (member == "DisplayDateEnd")
        {
            return object.Equals(target.DisplayDateEnd, value);
        }
        if (member == "FirstDayOfWeek")
        {
            return object.Equals(target.FirstDayOfWeek, value);
        }
        if (member == "IsDropDownOpen")
        {
            return object.Equals(target.IsDropDownOpen, value);
        }
        if (member == "IsTodayHighlighted")
        {
            return object.Equals(target.IsTodayHighlighted, value);
        }
        if (member == "SelectedDate")
        {
            return object.Equals(target.SelectedDate, value);
        }
        if (member == "SelectedDateFormat")
        {
            return object.Equals(target.SelectedDateFormat, value);
        }
        if (member == "CustomDateFormatString")
        {
            return object.Equals(target.CustomDateFormatString, value);
        }
        if (member == "Text")
        {
            return object.Equals(target.Text, value);
        }
        if (member == "Watermark")
        {
            return object.Equals(target.Watermark, value);
        }
        if (member == "UseFloatingWatermark")
        {
            return object.Equals(target.UseFloatingWatermark, value);
        }
        if (member == "HorizontalContentAlignment")
        {
            return object.Equals(target.HorizontalContentAlignment, value);
        }
        if (member == "VerticalContentAlignment")
        {
            return object.Equals(target.VerticalContentAlignment, value);
        }
        TemplatedControlConverter.MemberHasValue(target, member, value);
        throw new($"Member not found: {member}");
    }
}
