// <auto-generated />
class CalendarItemConverter :
    WriteOnlyJsonConverter<CalendarItem>
{
    public override void Write(VerifyJsonWriter writer, CalendarItem value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TemplatedControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, CalendarItem value)
    {
        if (!object.Equals(CalendarItem.HeaderBackgroundProperty.GetDefaultValue(typeof(CalendarItem)), value.HeaderBackground))
        {
            writer.WriteMember(value, value.HeaderBackground, "HeaderBackground");
        }
        if (!object.Equals(CalendarItem.DayTitleTemplateProperty.GetDefaultValue(typeof(CalendarItem)), value.DayTitleTemplate))
        {
            writer.WriteMember(value, value.DayTitleTemplate, "DayTitleTemplate");
        }
    }
}
