// <auto-generated />
#nullable enable
class CanvasConverter :
    WriteOnlyJsonConverter<Canvas>
{
    public override void Write(VerifyJsonWriter writer, Canvas value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Canvas value)
    {
        var type = typeof(Canvas);
    }
}
