// <auto-generated />
#nullable enable
class CarouselConverter :
    WriteOnlyJsonConverter<Carousel>
{
    public override void Write(VerifyJsonWriter writer, Carousel value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        SelectingItemsControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Carousel value)
    {
        if (!object.Equals(Carousel.PageTransitionProperty.GetDefaultValue(typeof(Carousel)), value.PageTransition))
        {
            writer.WriteMember(value, value.PageTransition, "PageTransition");
        }
    }

    public static bool MemberHasValue(Carousel target, string member, object? value)
    {
        if (member == "PageTransition")
        {
            return object.Equals(target.PageTransition, value);
        }
        throw new($"Member not found: {member}");
    }
}
