// <auto-generated />
#nullable enable
class ChromeOverlayLayerConverter :
    WriteOnlyJsonConverter<ChromeOverlayLayer>
{
    public override void Write(VerifyJsonWriter writer, ChromeOverlayLayer value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ChromeOverlayLayer value)
    {
        var type = typeof(ChromeOverlayLayer);
    }
}
