// <auto-generated />
#nullable enable
class ColorViewConverter :
    WriteOnlyJsonConverter<ColorView>
{
    public override void Write(VerifyJsonWriter writer, ColorView value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TemplatedControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ColorView value)
    {
        if (!object.Equals(ColorView.ColorProperty.GetDefaultValue(typeof(ColorView)), value.Color))
        {
            writer.WriteMember(value, value.Color, "Color");
        }
        if (!object.Equals(ColorView.ColorModelProperty.GetDefaultValue(typeof(ColorView)), value.ColorModel))
        {
            writer.WriteMember(value, value.ColorModel, "ColorModel");
        }
        if (!object.Equals(ColorView.ColorSpectrumComponentsProperty.GetDefaultValue(typeof(ColorView)), value.ColorSpectrumComponents))
        {
            writer.WriteMember(value, value.ColorSpectrumComponents, "ColorSpectrumComponents");
        }
        if (!object.Equals(ColorView.ColorSpectrumShapeProperty.GetDefaultValue(typeof(ColorView)), value.ColorSpectrumShape))
        {
            writer.WriteMember(value, value.ColorSpectrumShape, "ColorSpectrumShape");
        }
        if (!object.Equals(ColorView.HexInputAlphaPositionProperty.GetDefaultValue(typeof(ColorView)), value.HexInputAlphaPosition))
        {
            writer.WriteMember(value, value.HexInputAlphaPosition, "HexInputAlphaPosition");
        }
        if (!object.Equals(ColorView.HsvColorProperty.GetDefaultValue(typeof(ColorView)), value.HsvColor))
        {
            writer.WriteMember(value, value.HsvColor, "HsvColor");
        }
        if (!object.Equals(ColorView.IsAccentColorsVisibleProperty.GetDefaultValue(typeof(ColorView)), value.IsAccentColorsVisible))
        {
            writer.WriteMember(value, value.IsAccentColorsVisible, "IsAccentColorsVisible");
        }
        if (!object.Equals(ColorView.IsAlphaEnabledProperty.GetDefaultValue(typeof(ColorView)), value.IsAlphaEnabled))
        {
            writer.WriteMember(value, value.IsAlphaEnabled, "IsAlphaEnabled");
        }
        if (!object.Equals(ColorView.IsAlphaVisibleProperty.GetDefaultValue(typeof(ColorView)), value.IsAlphaVisible))
        {
            writer.WriteMember(value, value.IsAlphaVisible, "IsAlphaVisible");
        }
        if (!object.Equals(ColorView.IsColorComponentsVisibleProperty.GetDefaultValue(typeof(ColorView)), value.IsColorComponentsVisible))
        {
            writer.WriteMember(value, value.IsColorComponentsVisible, "IsColorComponentsVisible");
        }
        if (!object.Equals(ColorView.IsColorModelVisibleProperty.GetDefaultValue(typeof(ColorView)), value.IsColorModelVisible))
        {
            writer.WriteMember(value, value.IsColorModelVisible, "IsColorModelVisible");
        }
        if (!object.Equals(ColorView.IsColorPaletteVisibleProperty.GetDefaultValue(typeof(ColorView)), value.IsColorPaletteVisible))
        {
            writer.WriteMember(value, value.IsColorPaletteVisible, "IsColorPaletteVisible");
        }
        if (!object.Equals(ColorView.IsColorPreviewVisibleProperty.GetDefaultValue(typeof(ColorView)), value.IsColorPreviewVisible))
        {
            writer.WriteMember(value, value.IsColorPreviewVisible, "IsColorPreviewVisible");
        }
        if (!object.Equals(ColorView.IsColorSpectrumVisibleProperty.GetDefaultValue(typeof(ColorView)), value.IsColorSpectrumVisible))
        {
            writer.WriteMember(value, value.IsColorSpectrumVisible, "IsColorSpectrumVisible");
        }
        if (!object.Equals(ColorView.IsColorSpectrumSliderVisibleProperty.GetDefaultValue(typeof(ColorView)), value.IsColorSpectrumSliderVisible))
        {
            writer.WriteMember(value, value.IsColorSpectrumSliderVisible, "IsColorSpectrumSliderVisible");
        }
        if (!object.Equals(ColorView.IsComponentSliderVisibleProperty.GetDefaultValue(typeof(ColorView)), value.IsComponentSliderVisible))
        {
            writer.WriteMember(value, value.IsComponentSliderVisible, "IsComponentSliderVisible");
        }
        if (!object.Equals(ColorView.IsComponentTextInputVisibleProperty.GetDefaultValue(typeof(ColorView)), value.IsComponentTextInputVisible))
        {
            writer.WriteMember(value, value.IsComponentTextInputVisible, "IsComponentTextInputVisible");
        }
        if (!object.Equals(ColorView.IsHexInputVisibleProperty.GetDefaultValue(typeof(ColorView)), value.IsHexInputVisible))
        {
            writer.WriteMember(value, value.IsHexInputVisible, "IsHexInputVisible");
        }
        if (!object.Equals(ColorView.MaxHueProperty.GetDefaultValue(typeof(ColorView)), value.MaxHue))
        {
            writer.WriteMember(value, value.MaxHue, "MaxHue");
        }
        if (!object.Equals(ColorView.MaxSaturationProperty.GetDefaultValue(typeof(ColorView)), value.MaxSaturation))
        {
            writer.WriteMember(value, value.MaxSaturation, "MaxSaturation");
        }
        if (!object.Equals(ColorView.MaxValueProperty.GetDefaultValue(typeof(ColorView)), value.MaxValue))
        {
            writer.WriteMember(value, value.MaxValue, "MaxValue");
        }
        if (!object.Equals(ColorView.MinHueProperty.GetDefaultValue(typeof(ColorView)), value.MinHue))
        {
            writer.WriteMember(value, value.MinHue, "MinHue");
        }
        if (!object.Equals(ColorView.MinSaturationProperty.GetDefaultValue(typeof(ColorView)), value.MinSaturation))
        {
            writer.WriteMember(value, value.MinSaturation, "MinSaturation");
        }
        if (!object.Equals(ColorView.MinValueProperty.GetDefaultValue(typeof(ColorView)), value.MinValue))
        {
            writer.WriteMember(value, value.MinValue, "MinValue");
        }
        if (!object.Equals(ColorView.PaletteColorsProperty.GetDefaultValue(typeof(ColorView)), value.PaletteColors))
        {
            writer.WriteMember(value, value.PaletteColors, "PaletteColors");
        }
        if (!object.Equals(ColorView.PaletteColumnCountProperty.GetDefaultValue(typeof(ColorView)), value.PaletteColumnCount))
        {
            writer.WriteMember(value, value.PaletteColumnCount, "PaletteColumnCount");
        }
        if (!object.Equals(ColorView.PaletteProperty.GetDefaultValue(typeof(ColorView)), value.Palette))
        {
            writer.WriteMember(value, value.Palette, "Palette");
        }
        if (!object.Equals(ColorView.SelectedIndexProperty.GetDefaultValue(typeof(ColorView)), value.SelectedIndex))
        {
            writer.WriteMember(value, value.SelectedIndex, "SelectedIndex");
        }
    }

    public static bool MemberHasValue(ColorView target, string member, object? value)
    {
        if (member == "Color")
        {
            return object.Equals(target.Color, value);
        }
        if (member == "ColorModel")
        {
            return object.Equals(target.ColorModel, value);
        }
        if (member == "ColorSpectrumComponents")
        {
            return object.Equals(target.ColorSpectrumComponents, value);
        }
        if (member == "ColorSpectrumShape")
        {
            return object.Equals(target.ColorSpectrumShape, value);
        }
        if (member == "HexInputAlphaPosition")
        {
            return object.Equals(target.HexInputAlphaPosition, value);
        }
        if (member == "HsvColor")
        {
            return object.Equals(target.HsvColor, value);
        }
        if (member == "IsAccentColorsVisible")
        {
            return object.Equals(target.IsAccentColorsVisible, value);
        }
        if (member == "IsAlphaEnabled")
        {
            return object.Equals(target.IsAlphaEnabled, value);
        }
        if (member == "IsAlphaVisible")
        {
            return object.Equals(target.IsAlphaVisible, value);
        }
        if (member == "IsColorComponentsVisible")
        {
            return object.Equals(target.IsColorComponentsVisible, value);
        }
        if (member == "IsColorModelVisible")
        {
            return object.Equals(target.IsColorModelVisible, value);
        }
        if (member == "IsColorPaletteVisible")
        {
            return object.Equals(target.IsColorPaletteVisible, value);
        }
        if (member == "IsColorPreviewVisible")
        {
            return object.Equals(target.IsColorPreviewVisible, value);
        }
        if (member == "IsColorSpectrumVisible")
        {
            return object.Equals(target.IsColorSpectrumVisible, value);
        }
        if (member == "IsColorSpectrumSliderVisible")
        {
            return object.Equals(target.IsColorSpectrumSliderVisible, value);
        }
        if (member == "IsComponentSliderVisible")
        {
            return object.Equals(target.IsComponentSliderVisible, value);
        }
        if (member == "IsComponentTextInputVisible")
        {
            return object.Equals(target.IsComponentTextInputVisible, value);
        }
        if (member == "IsHexInputVisible")
        {
            return object.Equals(target.IsHexInputVisible, value);
        }
        if (member == "MaxHue")
        {
            return object.Equals(target.MaxHue, value);
        }
        if (member == "MaxSaturation")
        {
            return object.Equals(target.MaxSaturation, value);
        }
        if (member == "MaxValue")
        {
            return object.Equals(target.MaxValue, value);
        }
        if (member == "MinHue")
        {
            return object.Equals(target.MinHue, value);
        }
        if (member == "MinSaturation")
        {
            return object.Equals(target.MinSaturation, value);
        }
        if (member == "MinValue")
        {
            return object.Equals(target.MinValue, value);
        }
        if (member == "PaletteColors")
        {
            return object.Equals(target.PaletteColors, value);
        }
        if (member == "PaletteColumnCount")
        {
            return object.Equals(target.PaletteColumnCount, value);
        }
        if (member == "Palette")
        {
            return object.Equals(target.Palette, value);
        }
        if (member == "SelectedIndex")
        {
            return object.Equals(target.SelectedIndex, value);
        }
        throw new($"Member not found: {member}");
    }
}
