// <auto-generated />
#nullable enable
class ColorPickerConverter :
    WriteOnlyJsonConverter<ColorPicker>,
    IAvaloniaConverter<ColorPicker>
{
    public override void Write(VerifyJsonWriter writer, ColorPicker value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ColorViewConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ColorPicker value)
    {
    }

    public static bool MemberHasValue(ColorPicker target, string member, object? value)
    {
        ColorViewConverter.MemberHasValue(target, member, value);
        throw new($"Member not found: {member}");
    }
}
