// <auto-generated />
#nullable enable
class ColorPreviewerConverter :
    WriteOnlyJsonConverter<ColorPreviewer>
{
    public override void Write(VerifyJsonWriter writer, ColorPreviewer value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TemplatedControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ColorPreviewer value)
    {
        if (value.ShouldIncludeProperty(ColorPreviewer.HsvColorProperty))
        if (!object.Equals(ColorPreviewer.HsvColorProperty.GetDefaultValue(typeof(ColorPreviewer)), value.HsvColor))
        {
            writer.WriteMember(value, value.HsvColor, "HsvColor");
        }
        if (value.ShouldIncludeProperty(ColorPreviewer.IsAccentColorsVisibleProperty))
        if (!object.Equals(ColorPreviewer.IsAccentColorsVisibleProperty.GetDefaultValue(typeof(ColorPreviewer)), value.IsAccentColorsVisible))
        {
            writer.WriteMember(value, value.IsAccentColorsVisible, "IsAccentColorsVisible");
        }
    }
}
