// <auto-generated />
#nullable enable
class ComboBoxItemConverter :
    WriteOnlyJsonConverter<ComboBoxItem>
{
    public override void Write(VerifyJsonWriter writer, ComboBoxItem value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ListBoxItemConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ComboBoxItem value)
    {
    }

    public static bool MemberHasValue(ComboBoxItem target, string member, object? value)
    {
        throw new($"Member not found: {member}");
    }
}
