// <auto-generated />
#nullable enable
class ComboBoxConverter :
    WriteOnlyJsonConverter<ComboBox>
{
    public override void Write(VerifyJsonWriter writer, ComboBox value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        SelectingItemsControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ComboBox value)
    {
        if (value.ShouldIncludeProperty(ComboBox.IsDropDownOpenProperty))
        if (!object.Equals(ComboBox.IsDropDownOpenProperty.GetDefaultValue(typeof(ComboBox)), value.IsDropDownOpen))
        {
            writer.WriteMember(value, value.IsDropDownOpen, "IsDropDownOpen");
        }
        if (value.ShouldIncludeProperty(ComboBox.MaxDropDownHeightProperty))
        if (!object.Equals(ComboBox.MaxDropDownHeightProperty.GetDefaultValue(typeof(ComboBox)), value.MaxDropDownHeight))
        {
            writer.WriteMember(value, value.MaxDropDownHeight, "MaxDropDownHeight");
        }
        if (value.ShouldIncludeProperty(ComboBox.SelectionBoxItemProperty))
        if (!object.Equals(ComboBox.SelectionBoxItemProperty.GetUnsetValue(typeof(ComboBox)), value.SelectionBoxItem))
        {
            writer.WriteMember(value, value.SelectionBoxItem, "SelectionBoxItem");
        }
        if (value.ShouldIncludeProperty(ComboBox.PlaceholderTextProperty))
        if (!object.Equals(ComboBox.PlaceholderTextProperty.GetDefaultValue(typeof(ComboBox)), value.PlaceholderText))
        {
            writer.WriteMember(value, value.PlaceholderText, "PlaceholderText");
        }
        if (value.ShouldIncludeProperty(ComboBox.PlaceholderForegroundProperty))
        if (!object.Equals(ComboBox.PlaceholderForegroundProperty.GetDefaultValue(typeof(ComboBox)), value.PlaceholderForeground))
        {
            writer.WriteMember(value, value.PlaceholderForeground, "PlaceholderForeground");
        }
        if (value.ShouldIncludeProperty(ComboBox.HorizontalContentAlignmentProperty))
        if (!object.Equals(ComboBox.HorizontalContentAlignmentProperty.GetDefaultValue(typeof(ComboBox)), value.HorizontalContentAlignment))
        {
            writer.WriteMember(value, value.HorizontalContentAlignment, "HorizontalContentAlignment");
        }
        if (value.ShouldIncludeProperty(ComboBox.VerticalContentAlignmentProperty))
        if (!object.Equals(ComboBox.VerticalContentAlignmentProperty.GetDefaultValue(typeof(ComboBox)), value.VerticalContentAlignment))
        {
            writer.WriteMember(value, value.VerticalContentAlignment, "VerticalContentAlignment");
        }
    }
}
