// <auto-generated />
#nullable enable
class ContextMenuConverter :
    WriteOnlyJsonConverter<ContextMenu>
{
    public override void Write(VerifyJsonWriter writer, ContextMenu value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        MenuBaseConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ContextMenu value)
    {
        if (!object.Equals(ContextMenu.HorizontalOffsetProperty.GetDefaultValue(typeof(ContextMenu)), value.HorizontalOffset))
        {
            writer.WriteMember(value, value.HorizontalOffset, "HorizontalOffset");
        }
        if (!object.Equals(ContextMenu.VerticalOffsetProperty.GetDefaultValue(typeof(ContextMenu)), value.VerticalOffset))
        {
            writer.WriteMember(value, value.VerticalOffset, "VerticalOffset");
        }
        if (!object.Equals(ContextMenu.PlacementAnchorProperty.GetDefaultValue(typeof(ContextMenu)), value.PlacementAnchor))
        {
            writer.WriteMember(value, value.PlacementAnchor, "PlacementAnchor");
        }
        if (!object.Equals(ContextMenu.PlacementConstraintAdjustmentProperty.GetDefaultValue(typeof(ContextMenu)), value.PlacementConstraintAdjustment))
        {
            writer.WriteMember(value, value.PlacementConstraintAdjustment, "PlacementConstraintAdjustment");
        }
        if (!object.Equals(ContextMenu.PlacementGravityProperty.GetDefaultValue(typeof(ContextMenu)), value.PlacementGravity))
        {
            writer.WriteMember(value, value.PlacementGravity, "PlacementGravity");
        }
        if (!object.Equals(ContextMenu.PlacementProperty.GetDefaultValue(typeof(ContextMenu)), value.Placement))
        {
            writer.WriteMember(value, value.Placement, "Placement");
        }
        if (!object.Equals(ContextMenu.WindowManagerAddShadowHintProperty.GetDefaultValue(typeof(ContextMenu)), value.WindowManagerAddShadowHint))
        {
            writer.WriteMember(value, value.WindowManagerAddShadowHint, "WindowManagerAddShadowHint");
        }
        if (!object.Equals(ContextMenu.PlacementRectProperty.GetDefaultValue(typeof(ContextMenu)), value.PlacementRect))
        {
            writer.WriteMember(value, value.PlacementRect, "PlacementRect");
        }
        if (!object.Equals(ContextMenu.PlacementTargetProperty.GetDefaultValue(typeof(ContextMenu)), value.PlacementTarget))
        {
            writer.WriteMember(value, value.PlacementTarget, "PlacementTarget");
        }
    }

    public static bool MemberHasValue(ContextMenu target, string member, object? value)
    {
        if (member == "HorizontalOffset")
        {
            return object.Equals(target.HorizontalOffset, value);
        }
        if (member == "VerticalOffset")
        {
            return object.Equals(target.VerticalOffset, value);
        }
        if (member == "PlacementAnchor")
        {
            return object.Equals(target.PlacementAnchor, value);
        }
        if (member == "PlacementConstraintAdjustment")
        {
            return object.Equals(target.PlacementConstraintAdjustment, value);
        }
        if (member == "PlacementGravity")
        {
            return object.Equals(target.PlacementGravity, value);
        }
        if (member == "Placement")
        {
            return object.Equals(target.Placement, value);
        }
        if (member == "WindowManagerAddShadowHint")
        {
            return object.Equals(target.WindowManagerAddShadowHint, value);
        }
        if (member == "PlacementRect")
        {
            return object.Equals(target.PlacementRect, value);
        }
        if (member == "PlacementTarget")
        {
            return object.Equals(target.PlacementTarget, value);
        }
        throw new($"Member not found: {member}");
    }
}
