// <auto-generated />
class DataGridRowConverter :
    WriteOnlyJsonConverter<DataGridRow>
{
    public override void Write(VerifyJsonWriter writer, DataGridRow value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TemplatedControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, DataGridRow value)
    {
        if (DataGridRow.HeaderProperty.GetDefaultValue(typeof(DataGridRow)) != value.Header)
        {
            writer.WriteMember(value, value.Header, "Header");
        }
        if (!DataGridRow.IsValidProperty.GetUnsetValue(typeof(DataGridRow)).Equals(value.IsValid))
        {
            writer.WriteMember(value, value.IsValid, "IsValid");
        }
        if (DataGridRow.DetailsTemplateProperty.GetDefaultValue(typeof(DataGridRow)) != value.DetailsTemplate)
        {
            writer.WriteMember(value, value.DetailsTemplate, "DetailsTemplate");
        }
        if (!DataGridRow.AreDetailsVisibleProperty.GetDefaultValue(typeof(DataGridRow)).Equals(value.AreDetailsVisible))
        {
            writer.WriteMember(value, value.AreDetailsVisible, "AreDetailsVisible");
        }
    }
}
