// <auto-generated />
#nullable enable
class DataGridRowConverter :
    WriteOnlyJsonConverter<DataGridRow>
{
    public override void Write(VerifyJsonWriter writer, DataGridRow value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TemplatedControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, DataGridRow value)
    {
        if (DataGridRow.HeaderProperty.ShouldIncludeProperty(value, value.Header))
        {
            writer.WriteMember(value, value.Header, "Header");
        }
        if (DataGridRow.IsValidProperty.ShouldIncludeProperty(value, value.IsValid))
        {
            writer.WriteMember(value, value.IsValid, "IsValid");
        }
        if (DataGridRow.DetailsTemplateProperty.ShouldIncludeProperty(value, value.DetailsTemplate))
        {
            writer.WriteMember(value, value.DetailsTemplate, "DetailsTemplate");
        }
        if (DataGridRow.AreDetailsVisibleProperty.ShouldIncludeProperty(value, value.AreDetailsVisible))
        {
            writer.WriteMember(value, value.AreDetailsVisible, "AreDetailsVisible");
        }
    }
}
