// <auto-generated />
#nullable enable
class DataGridCellConverter :
    WriteOnlyJsonConverter<DataGridCell>
{
    public override void Write(VerifyJsonWriter writer, DataGridCell value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, DataGridCell value)
    {
        var type = typeof(DataGridCell);
        if (DataGridCell.IsValidProperty.ShouldIncludeProperty(value, value.IsValid))
        {
            writer.WriteMember(value, value.IsValid, "IsValid");
        }
    }
}
