// <auto-generated />
#nullable enable
class DataValidationErrorsConverter :
    WriteOnlyJsonConverter<DataValidationErrors>
{
    public override void Write(VerifyJsonWriter writer, DataValidationErrors value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, DataValidationErrors value)
    {
        if (!object.Equals(DataValidationErrors.OwnerProperty.GetUnsetValue(typeof(DataValidationErrors)), value.Owner))
        {
            writer.WriteMember(value, value.Owner, "Owner");
        }
        if (!object.Equals(DataValidationErrors.ErrorTemplateProperty.GetDefaultValue(typeof(DataValidationErrors)), value.ErrorTemplate))
        {
            writer.WriteMember(value, value.ErrorTemplate, "ErrorTemplate");
        }
    }

    public static bool MemberHasValue(DataValidationErrors target, string member, object? value)
    {
        if (member == "Owner")
        {
            return object.Equals(target.Owner, value);
        }
        if (member == "ErrorTemplate")
        {
            return object.Equals(target.ErrorTemplate, value);
        }
        ContentControlConverter.MemberHasValue(target, member, value);
        throw new($"Member not found: {member}");
    }
}
