// <auto-generated />
#nullable enable
class DataGridRowHeaderConverter :
    WriteOnlyJsonConverter<DataGridRowHeader>
{
    public override void Write(VerifyJsonWriter writer, DataGridRowHeader value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, DataGridRowHeader value)
    {
        var type = typeof(DataGridRowHeader);
        if (value.ShouldIncludeProperty(DataGridRowHeader.SeparatorBrushProperty))
        if (!object.Equals(DataGridRowHeader.SeparatorBrushProperty.GetDefaultValue(type), value.SeparatorBrush))
        {
            writer.WriteMember(value, value.SeparatorBrush, "SeparatorBrush");
        }
        if (value.ShouldIncludeProperty(DataGridRowHeader.AreSeparatorsVisibleProperty))
        if (!object.Equals(DataGridRowHeader.AreSeparatorsVisibleProperty.GetDefaultValue(type), value.AreSeparatorsVisible))
        {
            writer.WriteMember(value, value.AreSeparatorsVisible, "AreSeparatorsVisible");
        }
    }
}
