// <auto-generated />
class DataGridRowHeaderConverter :
    WriteOnlyJsonConverter<DataGridRowHeader>
{
    public override void Write(VerifyJsonWriter writer, DataGridRowHeader value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, DataGridRowHeader value)
    {
        if (!object.Equals(DataGridRowHeader.SeparatorBrushProperty.GetDefaultValue(typeof(DataGridRowHeader)), value.SeparatorBrush))
        {
            writer.WriteMember(value, value.SeparatorBrush, "SeparatorBrush");
        }
        if (!object.Equals(DataGridRowHeader.AreSeparatorsVisibleProperty.GetDefaultValue(typeof(DataGridRowHeader)), value.AreSeparatorsVisible))
        {
            writer.WriteMember(value, value.AreSeparatorsVisible, "AreSeparatorsVisible");
        }
    }
}
