// <auto-generated />
class DataGridDetailsPresenterConverter :
    WriteOnlyJsonConverter<DataGridDetailsPresenter>
{
    public override void Write(VerifyJsonWriter writer, DataGridDetailsPresenter value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, DataGridDetailsPresenter value)
    {
        if (!DataGridDetailsPresenter.ContentHeightProperty.GetDefaultValue(typeof(DataGridDetailsPresenter)).Equals(value.ContentHeight))
        {
            writer.WriteMember(value, value.ContentHeight, "ContentHeight");
        }
    }
}
