// <auto-generated />
#nullable enable
class DateTimePickerPanelConverter :
    WriteOnlyJsonConverter<DateTimePickerPanel>
{
    public override void Write(VerifyJsonWriter writer, DateTimePickerPanel value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, DateTimePickerPanel value)
    {
        var type = typeof(DateTimePickerPanel);
        if (value.ShouldIncludeProperty(DateTimePickerPanel.PanelTypeProperty))
        if (!object.Equals(DateTimePickerPanel.PanelTypeProperty.GetDefaultValue(type), value.PanelType))
        {
            writer.WriteMember(value, value.PanelType, "PanelType");
        }
        if (value.ShouldIncludeProperty(DateTimePickerPanel.ItemHeightProperty))
        if (!object.Equals(DateTimePickerPanel.ItemHeightProperty.GetDefaultValue(type), value.ItemHeight))
        {
            writer.WriteMember(value, value.ItemHeight, "ItemHeight");
        }
        if (value.ShouldIncludeProperty(DateTimePickerPanel.ItemFormatProperty))
        if (!object.Equals(DateTimePickerPanel.ItemFormatProperty.GetDefaultValue(type), value.ItemFormat))
        {
            writer.WriteMember(value, value.ItemFormat, "ItemFormat");
        }
        if (value.ShouldIncludeProperty(DateTimePickerPanel.ShouldLoopProperty))
        if (!object.Equals(DateTimePickerPanel.ShouldLoopProperty.GetDefaultValue(type), value.ShouldLoop))
        {
            writer.WriteMember(value, value.ShouldLoop, "ShouldLoop");
        }
        writer.WriteMember(value, value.MinimumValue, "MinimumValue");
        writer.WriteMember(value, value.MaximumValue, "MaximumValue");
        writer.WriteMember(value, value.SelectedValue, "SelectedValue");
        writer.WriteMember(value, value.Increment, "Increment");
        writer.WriteMember(value, value.Offset, "Offset");
        writer.WriteMember(value, value.CanHorizontallyScroll, "CanHorizontallyScroll");
        writer.WriteMember(value, value.CanVerticallyScroll, "CanVerticallyScroll");
        writer.WriteMember(value, value.IsLogicalScrollEnabled, "IsLogicalScrollEnabled");
        writer.WriteMember(value, value.ScrollSize, "ScrollSize");
        writer.WriteMember(value, value.PageScrollSize, "PageScrollSize");
        writer.WriteMember(value, value.Extent, "Extent");
        writer.WriteMember(value, value.Viewport, "Viewport");
    }
}
