// <auto-generated />
#nullable enable
class DecoratorConverter :
    WriteOnlyJsonConverter<Decorator>
{
    public override void Write(VerifyJsonWriter writer, Decorator value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Decorator value)
    {
        if (value.ShouldIncludeProperty(Decorator.ChildProperty))
        if (!object.Equals(Decorator.ChildProperty.GetDefaultValue(typeof(Decorator)), value.Child))
        {
            writer.WriteMember(value, value.Child, "Child");
        }
        if (value.ShouldIncludeProperty(Decorator.PaddingProperty))
        if (!object.Equals(Decorator.PaddingProperty.GetDefaultValue(typeof(Decorator)), value.Padding))
        {
            writer.WriteMember(value, value.Padding, "Padding");
        }
    }
}
