// <auto-generated />
#nullable enable
class DropDownButtonConverter :
    WriteOnlyJsonConverter<DropDownButton>,
    IAvaloniaConverter<DropDownButton>
{
    public override void Write(VerifyJsonWriter writer, DropDownButton value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ButtonConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, DropDownButton value)
    {
    }

    public static bool MemberHasValue(DropDownButton target, string member, object? value)
    {
        ButtonConverter.MemberHasValue(target, member, value);
        throw new($"Member not found: {member}");
    }
}
