// <auto-generated />
#nullable enable
class ExpanderConverter :
    WriteOnlyJsonConverter<Expander>
{
    public override void Write(VerifyJsonWriter writer, Expander value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        HeaderedContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Expander value)
    {
        if (Expander.ContentTransitionProperty.ShouldIncludeProperty(value, value.ContentTransition))
        {
            writer.WriteMember(value, value.ContentTransition, "ContentTransition");
        }
        if (Expander.ExpandDirectionProperty.ShouldIncludeProperty(value, value.ExpandDirection))
        {
            writer.WriteMember(value, value.ExpandDirection, "ExpandDirection");
        }
        if (Expander.IsExpandedProperty.ShouldIncludeProperty(value, value.IsExpanded))
        {
            writer.WriteMember(value, value.IsExpanded, "IsExpanded");
        }
    }
}
