// <auto-generated />
#nullable enable
class ExperimentalAcrylicBorderConverter :
    WriteOnlyJsonConverter<ExperimentalAcrylicBorder>
{
    public override void Write(VerifyJsonWriter writer, ExperimentalAcrylicBorder value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        DecoratorConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ExperimentalAcrylicBorder value)
    {
        var type = typeof(ExperimentalAcrylicBorder);
        if (value.ShouldIncludeProperty(ExperimentalAcrylicBorder.CornerRadiusProperty))
        if (!object.Equals(ExperimentalAcrylicBorder.CornerRadiusProperty.GetDefaultValue(type), value.CornerRadius))
        {
            writer.WriteMember(value, value.CornerRadius, "CornerRadius");
        }
        if (value.ShouldIncludeProperty(ExperimentalAcrylicBorder.MaterialProperty))
        if (!object.Equals(ExperimentalAcrylicBorder.MaterialProperty.GetDefaultValue(type), value.Material))
        {
            writer.WriteMember(value, value.Material, "Material");
        }
    }
}
