// <auto-generated />
#nullable enable
class ExperimentalAcrylicBorderConverter :
    WriteOnlyJsonConverter<ExperimentalAcrylicBorder>,
    IAvaloniaConverter<ExperimentalAcrylicBorder>
{
    public override void Write(VerifyJsonWriter writer, ExperimentalAcrylicBorder value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        DecoratorConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ExperimentalAcrylicBorder value)
    {
        if (value.ShouldIncludeProperty(ExperimentalAcrylicBorder.CornerRadiusProperty))
        if (!object.Equals(ExperimentalAcrylicBorder.CornerRadiusProperty.GetDefaultValue(typeof(ExperimentalAcrylicBorder)), value.CornerRadius))
        {
            writer.WriteMember(value, value.CornerRadius, "CornerRadius");
        }
        if (value.ShouldIncludeProperty(ExperimentalAcrylicBorder.MaterialProperty))
        if (!object.Equals(ExperimentalAcrylicBorder.MaterialProperty.GetDefaultValue(typeof(ExperimentalAcrylicBorder)), value.Material))
        {
            writer.WriteMember(value, value.Material, "Material");
        }
    }

    public static bool MemberHasValue(ExperimentalAcrylicBorder target, string member, object? value)
    {
        if (member == "CornerRadius")
        {
            return object.Equals(target.CornerRadius, value);
        }
        if (member == "Material")
        {
            return object.Equals(target.Material, value);
        }
        DecoratorConverter.MemberHasValue(target, member, value);
        throw new($"Member not found: {member}");
    }
}
