// <auto-generated />
#nullable enable
class GridConverter :
    WriteOnlyJsonConverter<Grid>
{
    public override void Write(VerifyJsonWriter writer, Grid value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Grid value)
    {
        if (value.ShouldIncludeProperty(Grid.ShowGridLinesProperty))
        if (!object.Equals(Grid.ShowGridLinesProperty.GetDefaultValue(typeof(Grid)), value.ShowGridLines))
        {
            writer.WriteMember(value, value.ShowGridLines, "ShowGridLines");
        }
        writer.WriteMember(value, value.ColumnDefinitions, "ColumnDefinitions");
        writer.WriteMember(value, value.RowDefinitions, "RowDefinitions");
    }
}
