// <auto-generated />
#nullable enable
class HeaderedContentControlConverter :
    WriteOnlyJsonConverter<HeaderedContentControl>
{
    public override void Write(VerifyJsonWriter writer, HeaderedContentControl value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, HeaderedContentControl value)
    {
        if (value.ShouldIncludeProperty(HeaderedContentControl.HeaderProperty))
        if (!object.Equals(HeaderedContentControl.HeaderProperty.GetDefaultValue(typeof(HeaderedContentControl)), value.Header))
        {
            writer.WriteMember(value, value.Header, "Header");
        }
        writer.WriteMember(value, value.HeaderPresenter, "HeaderPresenter");
        if (value.ShouldIncludeProperty(HeaderedContentControl.HeaderTemplateProperty))
        if (!object.Equals(HeaderedContentControl.HeaderTemplateProperty.GetDefaultValue(typeof(HeaderedContentControl)), value.HeaderTemplate))
        {
            writer.WriteMember(value, value.HeaderTemplate, "HeaderTemplate");
        }
    }
}
