// <auto-generated />
#nullable enable
class HeaderedItemsControlConverter :
    WriteOnlyJsonConverter<HeaderedItemsControl>
{
    public override void Write(VerifyJsonWriter writer, HeaderedItemsControl value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ItemsControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, HeaderedItemsControl value)
    {
        var type = typeof(HeaderedItemsControl);
        if (HeaderedItemsControl.HeaderProperty.ShouldIncludeProperty(value, value.Header))
        {
            writer.WriteMember(value, value.Header, "Header");
        }
        if (HeaderedItemsControl.HeaderTemplateProperty.ShouldIncludeProperty(value, value.HeaderTemplate))
        {
            writer.WriteMember(value, value.HeaderTemplate, "HeaderTemplate");
        }
    }
}
