// <auto-generated />
class HeaderedItemsControlConverter :
    WriteOnlyJsonConverter<HeaderedItemsControl>
{
    public override void Write(VerifyJsonWriter writer, HeaderedItemsControl value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ItemsControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, HeaderedItemsControl value)
    {
        if (HeaderedItemsControl.HeaderProperty.GetDefaultValue(typeof(HeaderedItemsControl)) != value.Header)
        {
            writer.WriteMember(value, value.Header, "Header");
        }
        if (HeaderedItemsControl.HeaderTemplateProperty.GetDefaultValue(typeof(HeaderedItemsControl)) != value.HeaderTemplate)
        {
            writer.WriteMember(value, value.HeaderTemplate, "HeaderTemplate");
        }
         writer.WriteMember(value, value.HeaderPresenter, "HeaderPresenter");
    }
}
