// <auto-generated />
#nullable enable
class ImageConverter :
    WriteOnlyJsonConverter<Image>
{
    public override void Write(VerifyJsonWriter writer, Image value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Image value)
    {
        var type = typeof(Image);
        if (Image.SourceProperty.ShouldIncludeProperty(value, value.Source))
        {
            writer.WriteMember(value, value.Source, "Source");
        }
        if (Image.StretchProperty.ShouldIncludeProperty(value, value.Stretch))
        {
            writer.WriteMember(value, value.Stretch, "Stretch");
        }
        if (Image.StretchDirectionProperty.ShouldIncludeProperty(value, value.StretchDirection))
        {
            writer.WriteMember(value, value.StretchDirection, "StretchDirection");
        }
    }
}
