// <auto-generated />
#nullable enable
class ImageConverter :
    WriteOnlyJsonConverter<Image>
{
    public override void Write(VerifyJsonWriter writer, Image value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Image value)
    {
        if (!object.Equals(Image.SourceProperty.GetDefaultValue(typeof(Image)), value.Source))
        {
            writer.WriteMember(value, value.Source, "Source");
        }
        if (!object.Equals(Image.StretchProperty.GetDefaultValue(typeof(Image)), value.Stretch))
        {
            writer.WriteMember(value, value.Stretch, "Stretch");
        }
        if (!object.Equals(Image.StretchDirectionProperty.GetDefaultValue(typeof(Image)), value.StretchDirection))
        {
            writer.WriteMember(value, value.StretchDirection, "StretchDirection");
        }
    }

    public static bool MemberHasValue(Image target, string member, object? value)
    {
        if (member == "Source")
        {
            return object.Equals(target.Source, value);
        }
        if (member == "Stretch")
        {
            return object.Equals(target.Stretch, value);
        }
        if (member == "StretchDirection")
        {
            return object.Equals(target.StretchDirection, value);
        }
        ControlConverter.MemberHasValue(target, member, value);
        throw new($"Member not found: {member}");
    }
}
