// <auto-generated />
#nullable enable
class ImageConverter :
    WriteOnlyJsonConverter<Image>
{
    public override void Write(VerifyJsonWriter writer, Image value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Image value)
    {
        var type = typeof(Image);
        if (value.ShouldIncludeProperty(Image.SourceProperty))
        if (!object.Equals(Image.SourceProperty.GetDefaultValue(type), value.Source))
        {
            writer.WriteMember(value, value.Source, "Source");
        }
        if (value.ShouldIncludeProperty(Image.StretchProperty))
        if (!object.Equals(Image.StretchProperty.GetDefaultValue(type), value.Stretch))
        {
            writer.WriteMember(value, value.Stretch, "Stretch");
        }
        if (value.ShouldIncludeProperty(Image.StretchDirectionProperty))
        if (!object.Equals(Image.StretchDirectionProperty.GetDefaultValue(type), value.StretchDirection))
        {
            writer.WriteMember(value, value.StretchDirection, "StretchDirection");
        }
    }
}
