// <auto-generated />
#nullable enable
class InteractiveConverter :
    WriteOnlyJsonConverter<Interactive>
{
    public override void Write(VerifyJsonWriter writer, Interactive value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        LayoutableConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Interactive value)
    {
    }

    public static bool MemberHasValue(Interactive target, string member, object? value)
    {
        throw new($"Member not found: {member}");
    }
}
