// <auto-generated />
#nullable enable
class LabelConverter :
    WriteOnlyJsonConverter<Label>
{
    public override void Write(VerifyJsonWriter writer, Label value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Label value)
    {
        if (Label.TargetProperty.ShouldIncludeProperty(value, value.Target))
        {
            writer.WriteMember(value, value.Target, "Target");
        }
    }
}
