// <auto-generated />
#nullable enable
class LayoutTransformControlConverter :
    WriteOnlyJsonConverter<LayoutTransformControl>
{
    public override void Write(VerifyJsonWriter writer, LayoutTransformControl value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        DecoratorConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, LayoutTransformControl value)
    {
        var type = typeof(LayoutTransformControl);
        if (value.ShouldIncludeProperty(LayoutTransformControl.LayoutTransformProperty))
        if (!object.Equals(LayoutTransformControl.LayoutTransformProperty.GetDefaultValue(type), value.LayoutTransform))
        {
            writer.WriteMember(value, value.LayoutTransform, "LayoutTransform");
        }
        if (value.ShouldIncludeProperty(LayoutTransformControl.UseRenderTransformProperty))
        if (!object.Equals(LayoutTransformControl.UseRenderTransformProperty.GetDefaultValue(type), value.UseRenderTransform))
        {
            writer.WriteMember(value, value.UseRenderTransform, "UseRenderTransform");
        }
        writer.WriteMember(value, value.TransformRoot, "TransformRoot");
    }
}
