// <auto-generated />
class LayoutableConverter :
    WriteOnlyJsonConverter<Layoutable>
{
    public override void Write(VerifyJsonWriter writer, Layoutable value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        VisualConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Layoutable value)
    {
        if (!object.Equals(Layoutable.WidthProperty.GetDefaultValue(typeof(Layoutable)), value.Width))
        {
            writer.WriteMember(value, value.Width, "Width");
        }
        if (!object.Equals(Layoutable.HeightProperty.GetDefaultValue(typeof(Layoutable)), value.Height))
        {
            writer.WriteMember(value, value.Height, "Height");
        }
        if (!object.Equals(Layoutable.MinWidthProperty.GetDefaultValue(typeof(Layoutable)), value.MinWidth))
        {
            writer.WriteMember(value, value.MinWidth, "MinWidth");
        }
        if (!object.Equals(Layoutable.MaxWidthProperty.GetDefaultValue(typeof(Layoutable)), value.MaxWidth))
        {
            writer.WriteMember(value, value.MaxWidth, "MaxWidth");
        }
        if (!object.Equals(Layoutable.MinHeightProperty.GetDefaultValue(typeof(Layoutable)), value.MinHeight))
        {
            writer.WriteMember(value, value.MinHeight, "MinHeight");
        }
        if (!object.Equals(Layoutable.MaxHeightProperty.GetDefaultValue(typeof(Layoutable)), value.MaxHeight))
        {
            writer.WriteMember(value, value.MaxHeight, "MaxHeight");
        }
        if (!object.Equals(Layoutable.MarginProperty.GetDefaultValue(typeof(Layoutable)), value.Margin))
        {
            writer.WriteMember(value, value.Margin, "Margin");
        }
        if (!object.Equals(Layoutable.HorizontalAlignmentProperty.GetDefaultValue(typeof(Layoutable)), value.HorizontalAlignment))
        {
            writer.WriteMember(value, value.HorizontalAlignment, "HorizontalAlignment");
        }
        if (!object.Equals(Layoutable.VerticalAlignmentProperty.GetDefaultValue(typeof(Layoutable)), value.VerticalAlignment))
        {
            writer.WriteMember(value, value.VerticalAlignment, "VerticalAlignment");
        }
        if (!object.Equals(Layoutable.DesiredSizeProperty.GetUnsetValue(typeof(Layoutable)), value.DesiredSize))
        {
            writer.WriteMember(value, value.DesiredSize, "DesiredSize");
        }
         writer.WriteMember(value, value.IsMeasureValid, "IsMeasureValid");
         writer.WriteMember(value, value.IsArrangeValid, "IsArrangeValid");
        if (!object.Equals(Layoutable.UseLayoutRoundingProperty.GetDefaultValue(typeof(Layoutable)), value.UseLayoutRounding))
        {
            writer.WriteMember(value, value.UseLayoutRounding, "UseLayoutRounding");
        }
    }
}
