// <auto-generated />
#nullable enable
class LineConverter :
    WriteOnlyJsonConverter<Line>
{
    public override void Write(VerifyJsonWriter writer, Line value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ShapeConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Line value)
    {
        var type = typeof(Line);
        if (Line.StartPointProperty.ShouldIncludeProperty(value, value.StartPoint))
        {
            writer.WriteMember(value, value.StartPoint, "StartPoint");
        }
        if (Line.EndPointProperty.ShouldIncludeProperty(value, value.EndPoint))
        {
            writer.WriteMember(value, value.EndPoint, "EndPoint");
        }
    }
}
