// <auto-generated />
class LineConverter :
    WriteOnlyJsonConverter<Line>
{
    public override void Write(VerifyJsonWriter writer, Line value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ShapeConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Line value)
    {
         if (!Line.StartPointProperty.GetDefaultValue(typeof(Line)).Equals(value.StartPoint))
         {
             writer.WriteMember(value, value.StartPoint, "StartPoint");
         }
         if (!Line.EndPointProperty.GetDefaultValue(typeof(Line)).Equals(value.EndPoint))
         {
             writer.WriteMember(value, value.EndPoint, "EndPoint");
         }
    }
}
