// <auto-generated />
#nullable enable
class ListBoxItemConverter :
    WriteOnlyJsonConverter<ListBoxItem>
{
    public override void Write(VerifyJsonWriter writer, ListBoxItem value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ListBoxItem value)
    {
        var type = typeof(ListBoxItem);
        if (ListBoxItem.IsSelectedProperty.ShouldIncludeProperty(value, value.IsSelected))
        {
            writer.WriteMember(value, value.IsSelected, "IsSelected");
        }
    }
}
