// <auto-generated />
#nullable enable
class ListBoxConverter :
    WriteOnlyJsonConverter<ListBox>
{
    public override void Write(VerifyJsonWriter writer, ListBox value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        SelectingItemsControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ListBox value)
    {
        if (ListBox.ScrollProperty.ShouldIncludeProperty(value, value.Scroll))
        {
            writer.WriteMember(value, value.Scroll, "Scroll");
        }
        if (ListBox.SelectedItemsProperty.ShouldIncludeProperty(value, value.SelectedItems))
        {
            writer.WriteMember(value, value.SelectedItems, "SelectedItems");
        }
        if (ListBox.SelectionProperty.ShouldIncludeProperty(value, value.Selection))
        {
            writer.WriteMember(value, value.Selection, "Selection");
        }
        if (ListBox.SelectionModeProperty.ShouldIncludeProperty(value, value.SelectionMode))
        {
            writer.WriteMember(value, value.SelectionMode, "SelectionMode");
        }
    }
}
