// <auto-generated />
class ListBoxConverter :
    WriteOnlyJsonConverter<ListBox>
{
    public override void Write(VerifyJsonWriter writer, ListBox value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        SelectingItemsControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ListBox value)
    {
        if (ListBox.ScrollProperty.GetUnsetValue(typeof(ListBox)) != value.Scroll)
        {
            writer.WriteMember(value, value.Scroll, "Scroll");
        }
        if (ListBox.SelectedItemsProperty.GetUnsetValue(typeof(ListBox)) != value.SelectedItems)
        {
            writer.WriteMember(value, value.SelectedItems, "SelectedItems");
        }
        if (ListBox.SelectionProperty.GetUnsetValue(typeof(ListBox)) != value.Selection)
        {
            writer.WriteMember(value, value.Selection, "Selection");
        }
         if (!ListBox.SelectionModeProperty.GetDefaultValue(typeof(ListBox)).Equals(value.SelectionMode))
         {
             writer.WriteMember(value, value.SelectionMode, "SelectionMode");
         }
    }
}
