// <auto-generated />
class ListBoxItemConverter :
    WriteOnlyJsonConverter<ListBoxItem>
{
    public override void Write(VerifyJsonWriter writer, ListBoxItem value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ListBoxItem value)
    {
        if (!object.Equals(ListBoxItem.IsSelectedProperty.GetDefaultValue(typeof(ListBoxItem)), value.IsSelected))
        {
            writer.WriteMember(value, value.IsSelected, "IsSelected");
        }
    }
}
