// <auto-generated />
#nullable enable
class MaskedTextBoxConverter :
    WriteOnlyJsonConverter<MaskedTextBox>
{
    public override void Write(VerifyJsonWriter writer, MaskedTextBox value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TextBoxConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, MaskedTextBox value)
    {
        var type = typeof(MaskedTextBox);
        if (value.ShouldIncludeProperty(MaskedTextBox.AsciiOnlyProperty))
        if (!object.Equals(MaskedTextBox.AsciiOnlyProperty.GetDefaultValue(type), value.AsciiOnly))
        {
            writer.WriteMember(value, value.AsciiOnly, "AsciiOnly");
        }
        if (value.ShouldIncludeProperty(MaskedTextBox.CultureProperty))
        if (!object.Equals(MaskedTextBox.CultureProperty.GetDefaultValue(type), value.Culture))
        {
            writer.WriteMember(value, value.Culture, "Culture");
        }
        if (value.ShouldIncludeProperty(MaskedTextBox.HidePromptOnLeaveProperty))
        if (!object.Equals(MaskedTextBox.HidePromptOnLeaveProperty.GetDefaultValue(type), value.HidePromptOnLeave))
        {
            writer.WriteMember(value, value.HidePromptOnLeave, "HidePromptOnLeave");
        }
        if (value.ShouldIncludeProperty(MaskedTextBox.MaskProperty))
        if (!object.Equals(MaskedTextBox.MaskProperty.GetDefaultValue(type), value.Mask))
        {
            writer.WriteMember(value, value.Mask, "Mask");
        }
        if (value.ShouldIncludeProperty(MaskedTextBox.MaskCompletedProperty))
        if (!object.Equals(MaskedTextBox.MaskCompletedProperty.GetUnsetValue(type), value.MaskCompleted))
        {
            writer.WriteMember(value, value.MaskCompleted, "MaskCompleted");
        }
        if (value.ShouldIncludeProperty(MaskedTextBox.MaskFullProperty))
        if (!object.Equals(MaskedTextBox.MaskFullProperty.GetUnsetValue(type), value.MaskFull))
        {
            writer.WriteMember(value, value.MaskFull, "MaskFull");
        }
        writer.WriteMember(value, value.MaskProvider, "MaskProvider");
        if (value.ShouldIncludeProperty(MaskedTextBox.PromptCharProperty))
        if (!object.Equals(MaskedTextBox.PromptCharProperty.GetDefaultValue(type), value.PromptChar))
        {
            writer.WriteMember(value, value.PromptChar, "PromptChar");
        }
        if (value.ShouldIncludeProperty(MaskedTextBox.ResetOnPromptProperty))
        if (!object.Equals(MaskedTextBox.ResetOnPromptProperty.GetDefaultValue(type), value.ResetOnPrompt))
        {
            writer.WriteMember(value, value.ResetOnPrompt, "ResetOnPrompt");
        }
        if (value.ShouldIncludeProperty(MaskedTextBox.ResetOnSpaceProperty))
        if (!object.Equals(MaskedTextBox.ResetOnSpaceProperty.GetDefaultValue(type), value.ResetOnSpace))
        {
            writer.WriteMember(value, value.ResetOnSpace, "ResetOnSpace");
        }
    }
}
