// <auto-generated />
#nullable enable
class MenuBaseConverter :
    WriteOnlyJsonConverter<MenuBase>
{
    public override void Write(VerifyJsonWriter writer, MenuBase value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        SelectingItemsControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, MenuBase value)
    {
        var type = typeof(MenuBase);
        if (value.ShouldIncludeProperty(MenuBase.IsOpenProperty))
        if (!object.Equals(MenuBase.IsOpenProperty.GetUnsetValue(type), value.IsOpen))
        {
            writer.WriteMember(value, value.IsOpen, "IsOpen");
        }
    }
}
