// <auto-generated />
#nullable enable
class MenuConverter :
    WriteOnlyJsonConverter<Menu>,
    IAvaloniaConverter<Menu>
{
    public override void Write(VerifyJsonWriter writer, Menu value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        MenuBaseConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Menu value)
    {
    }

    public static bool MemberHasValue(Menu target, string member, object? value)
    {
        MenuBaseConverter.MemberHasValue(target, member, value);
        throw new($"Member not found: {member}");
    }
}
