// <auto-generated />
class NativeMenuBarConverter :
    WriteOnlyJsonConverter<NativeMenuBar>
{
    public override void Write(VerifyJsonWriter writer, NativeMenuBar value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TemplatedControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, NativeMenuBar value)
    {
    }
}
