// <auto-generated />
#nullable enable
class NativeControlHostConverter :
    WriteOnlyJsonConverter<NativeControlHost>
{
    public override void Write(VerifyJsonWriter writer, NativeControlHost value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, NativeControlHost value)
    {
    }
}
