// <auto-generated />
#nullable enable
class NativeMenuBarConverter :
    WriteOnlyJsonConverter<NativeMenuBar>
{
    public override void Write(VerifyJsonWriter writer, NativeMenuBar value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TemplatedControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, NativeMenuBar value)
    {
    }

    public static bool MemberHasValue(NativeMenuBar target, string member, object? value)
    {
        throw new($"Member not found: {member}");
    }
}
