// <auto-generated />
#nullable enable
class NotificationCardConverter :
    WriteOnlyJsonConverter<NotificationCard>
{
    public override void Write(VerifyJsonWriter writer, NotificationCard value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, NotificationCard value)
    {
        var type = typeof(NotificationCard);
        if (NotificationCard.IsClosingProperty.ShouldIncludeProperty(value, value.IsClosing))
        {
            writer.WriteMember(value, value.IsClosing, "IsClosing");
        }
        if (NotificationCard.IsClosedProperty.ShouldIncludeProperty(value, value.IsClosed))
        {
            writer.WriteMember(value, value.IsClosed, "IsClosed");
        }
    }
}
