// <auto-generated />
#nullable enable
class OverlayPopupHostConverter :
    WriteOnlyJsonConverter<OverlayPopupHost>
{
    public override void Write(VerifyJsonWriter writer, OverlayPopupHost value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, OverlayPopupHost value)
    {
         writer.WriteMember(value, value.HostedVisualTreeRoot, "HostedVisualTreeRoot");
        if (!object.Equals(OverlayPopupHost.TransformProperty.GetDefaultValue(typeof(OverlayPopupHost)), value.Transform))
        {
            writer.WriteMember(value, value.Transform, "Transform");
        }
    }

    public static bool MemberHasValue(OverlayPopupHost target, string member, object? value)
    {
        if (member == "HostedVisualTreeRoot")
        {
            return object.Equals(target.HostedVisualTreeRoot, value);
        }
        if (member == "Transform")
        {
            return object.Equals(target.Transform, value);
        }
        throw new($"Member not found: {member}");
    }
}
