// <auto-generated />
#nullable enable
class OverlayPopupHostConverter :
    WriteOnlyJsonConverter<OverlayPopupHost>
{
    public override void Write(VerifyJsonWriter writer, OverlayPopupHost value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, OverlayPopupHost value)
    {
        writer.WriteMember(value, value.HostedVisualTreeRoot, "HostedVisualTreeRoot");
        if (value.ShouldIncludeProperty(OverlayPopupHost.TransformProperty))
        if (!object.Equals(OverlayPopupHost.TransformProperty.GetDefaultValue(typeof(OverlayPopupHost)), value.Transform))
        {
            writer.WriteMember(value, value.Transform, "Transform");
        }
    }
}
