// <auto-generated />
class PathConverter :
    WriteOnlyJsonConverter<Path>
{
    public override void Write(VerifyJsonWriter writer, Path value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ShapeConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Path value)
    {
        if (!object.Equals(Path.DataProperty.GetDefaultValue(typeof(Path)), value.Data))
        {
            writer.WriteMember(value, value.Data, "Data");
        }
    }
}
