// <auto-generated />
class PathIconConverter :
    WriteOnlyJsonConverter<PathIcon>
{
    public override void Write(VerifyJsonWriter writer, PathIcon value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        IconElementConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, PathIcon value)
    {
        if (PathIcon.DataProperty.GetDefaultValue(typeof(PathIcon)) != value.Data)
        {
            writer.WriteMember(value, value.Data, "Data");
        }
    }
}
