// <auto-generated />
class PopupRootConverter :
    WriteOnlyJsonConverter<PopupRoot>
{
    public override void Write(VerifyJsonWriter writer, PopupRoot value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        WindowBaseConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, PopupRoot value)
    {
        if (PopupRoot.TransformProperty.GetDefaultValue(typeof(PopupRoot)) != value.Transform)
        {
            writer.WriteMember(value, value.Transform, "Transform");
        }
         writer.WriteMember(value, value.ParentTopLevel, "ParentTopLevel");
    }
}
