// <auto-generated />
#nullable enable
class RadioButtonConverter :
    WriteOnlyJsonConverter<RadioButton>,
    IAvaloniaConverter<RadioButton>
{
    public override void Write(VerifyJsonWriter writer, RadioButton value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ToggleButtonConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, RadioButton value)
    {
        if (value.ShouldIncludeProperty(RadioButton.GroupNameProperty))
        if (!object.Equals(RadioButton.GroupNameProperty.GetDefaultValue(typeof(RadioButton)), value.GroupName))
        {
            writer.WriteMember(value, value.GroupName, "GroupName");
        }
    }

    public static bool MemberHasValue(RadioButton target, string member, object? value)
    {
        if (member == "GroupName")
        {
            return object.Equals(target.GroupName, value);
        }
        ToggleButtonConverter.MemberHasValue(target, member, value);
        throw new($"Member not found: {member}");
    }
}
