// <auto-generated />
#nullable enable
class RectangleConverter :
    WriteOnlyJsonConverter<Rectangle>,
    IAvaloniaConverter<Rectangle>
{
    public override void Write(VerifyJsonWriter writer, Rectangle value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ShapeConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Rectangle value)
    {
        if (value.ShouldIncludeProperty(Rectangle.RadiusXProperty))
        if (!object.Equals(Rectangle.RadiusXProperty.GetDefaultValue(typeof(Rectangle)), value.RadiusX))
        {
            writer.WriteMember(value, value.RadiusX, "RadiusX");
        }
        if (value.ShouldIncludeProperty(Rectangle.RadiusYProperty))
        if (!object.Equals(Rectangle.RadiusYProperty.GetDefaultValue(typeof(Rectangle)), value.RadiusY))
        {
            writer.WriteMember(value, value.RadiusY, "RadiusY");
        }
    }

    public static bool MemberHasValue(Rectangle target, string member, object? value)
    {
        if (member == "RadiusX")
        {
            return object.Equals(target.RadiusX, value);
        }
        if (member == "RadiusY")
        {
            return object.Equals(target.RadiusY, value);
        }
        ShapeConverter.MemberHasValue(target, member, value);
        throw new($"Member not found: {member}");
    }
}
