// <auto-generated />
#nullable enable
class RectangleConverter :
    WriteOnlyJsonConverter<Rectangle>
{
    public override void Write(VerifyJsonWriter writer, Rectangle value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ShapeConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Rectangle value)
    {
        var type = typeof(Rectangle);
        if (Rectangle.RadiusXProperty.ShouldIncludeProperty(value, value.RadiusX))
        {
            writer.WriteMember(value, value.RadiusX, "RadiusX");
        }
        if (Rectangle.RadiusYProperty.ShouldIncludeProperty(value, value.RadiusY))
        {
            writer.WriteMember(value, value.RadiusY, "RadiusY");
        }
    }
}
