// <auto-generated />
class RefreshContainerConverter :
    WriteOnlyJsonConverter<RefreshContainer>
{
    public override void Write(VerifyJsonWriter writer, RefreshContainer value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, RefreshContainer value)
    {
        if (!object.Equals(RefreshContainer.VisualizerProperty.GetUnsetValue(typeof(RefreshContainer)), value.Visualizer))
        {
            writer.WriteMember(value, value.Visualizer, "Visualizer");
        }
        if (!object.Equals(RefreshContainer.PullDirectionProperty.GetDefaultValue(typeof(RefreshContainer)), value.PullDirection))
        {
            writer.WriteMember(value, value.PullDirection, "PullDirection");
        }
    }
}
