// <auto-generated />
class RelativePanelConverter :
    WriteOnlyJsonConverter<RelativePanel>
{
    public override void Write(VerifyJsonWriter writer, RelativePanel value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, RelativePanel value)
    {
    }
}
