// <auto-generated />
#nullable enable
class RemoteWidgetConverter :
    WriteOnlyJsonConverter<RemoteWidget>
{
    public override void Write(VerifyJsonWriter writer, RemoteWidget value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, RemoteWidget value)
    {
        var type = typeof(RemoteWidget);
        writer.WriteMember(value, value.Mode, "Mode");
    }
}
