// <auto-generated />
#nullable enable
class RepeatButtonConverter :
    WriteOnlyJsonConverter<RepeatButton>
{
    public override void Write(VerifyJsonWriter writer, RepeatButton value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ButtonConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, RepeatButton value)
    {
        if (!object.Equals(RepeatButton.IntervalProperty.GetDefaultValue(typeof(RepeatButton)), value.Interval))
        {
            writer.WriteMember(value, value.Interval, "Interval");
        }
        if (!object.Equals(RepeatButton.DelayProperty.GetDefaultValue(typeof(RepeatButton)), value.Delay))
        {
            writer.WriteMember(value, value.Delay, "Delay");
        }
    }

    public static bool MemberHasValue(RepeatButton target, string member, object? value)
    {
        if (member == "Interval")
        {
            return object.Equals(target.Interval, value);
        }
        if (member == "Delay")
        {
            return object.Equals(target.Delay, value);
        }
        throw new($"Member not found: {member}");
    }
}
