// <auto-generated />
class RepeatButtonConverter :
    WriteOnlyJsonConverter<RepeatButton>
{
    public override void Write(VerifyJsonWriter writer, RepeatButton value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ButtonConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, RepeatButton value)
    {
        if (!RepeatButton.IntervalProperty.GetDefaultValue(typeof(RepeatButton)).Equals(value.Interval))
        {
            writer.WriteMember(value, value.Interval, "Interval");
        }
        if (!RepeatButton.DelayProperty.GetDefaultValue(typeof(RepeatButton)).Equals(value.Delay))
        {
            writer.WriteMember(value, value.Delay, "Delay");
        }
    }
}
