// <auto-generated />
class ReversibleStackPanelConverter :
    WriteOnlyJsonConverter<ReversibleStackPanel>
{
    public override void Write(VerifyJsonWriter writer, ReversibleStackPanel value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        StackPanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ReversibleStackPanel value)
    {
        if (!object.Equals(ReversibleStackPanel.ReverseOrderProperty.GetDefaultValue(typeof(ReversibleStackPanel)), value.ReverseOrder))
        {
            writer.WriteMember(value, value.ReverseOrder, "ReverseOrder");
        }
    }
}
