// <auto-generated />
class ScrollViewerConverter :
    WriteOnlyJsonConverter<ScrollViewer>
{
    public override void Write(VerifyJsonWriter writer, ScrollViewer value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ScrollViewer value)
    {
        if (!ScrollViewer.BringIntoViewOnFocusChangeProperty.GetDefaultValue(typeof(ScrollViewer)).Equals(value.BringIntoViewOnFocusChange))
        {
            writer.WriteMember(value, value.BringIntoViewOnFocusChange, "BringIntoViewOnFocusChange");
        }
        if (!ScrollViewer.ExtentProperty.GetUnsetValue(typeof(ScrollViewer)).Equals(value.Extent))
        {
            writer.WriteMember(value, value.Extent, "Extent");
        }
        if (!ScrollViewer.OffsetProperty.GetDefaultValue(typeof(ScrollViewer)).Equals(value.Offset))
        {
            writer.WriteMember(value, value.Offset, "Offset");
        }
        if (!ScrollViewer.ViewportProperty.GetUnsetValue(typeof(ScrollViewer)).Equals(value.Viewport))
        {
            writer.WriteMember(value, value.Viewport, "Viewport");
        }
        if (!ScrollViewer.LargeChangeProperty.GetUnsetValue(typeof(ScrollViewer)).Equals(value.LargeChange))
        {
            writer.WriteMember(value, value.LargeChange, "LargeChange");
        }
        if (!ScrollViewer.SmallChangeProperty.GetUnsetValue(typeof(ScrollViewer)).Equals(value.SmallChange))
        {
            writer.WriteMember(value, value.SmallChange, "SmallChange");
        }
        if (!ScrollViewer.HorizontalScrollBarVisibilityProperty.GetDefaultValue(typeof(ScrollViewer)).Equals(value.HorizontalScrollBarVisibility))
        {
            writer.WriteMember(value, value.HorizontalScrollBarVisibility, "HorizontalScrollBarVisibility");
        }
        if (!ScrollViewer.VerticalScrollBarVisibilityProperty.GetDefaultValue(typeof(ScrollViewer)).Equals(value.VerticalScrollBarVisibility))
        {
            writer.WriteMember(value, value.VerticalScrollBarVisibility, "VerticalScrollBarVisibility");
        }
         writer.WriteMember(value, value.CurrentAnchor, "CurrentAnchor");
        if (!ScrollViewer.ScrollBarMaximumProperty.GetUnsetValue(typeof(ScrollViewer)).Equals(value.ScrollBarMaximum))
        {
            writer.WriteMember(value, value.ScrollBarMaximum, "ScrollBarMaximum");
        }
        if (!ScrollViewer.IsExpandedProperty.GetUnsetValue(typeof(ScrollViewer)).Equals(value.IsExpanded))
        {
            writer.WriteMember(value, value.IsExpanded, "IsExpanded");
        }
        if (!ScrollViewer.HorizontalSnapPointsTypeProperty.GetDefaultValue(typeof(ScrollViewer)).Equals(value.HorizontalSnapPointsType))
        {
            writer.WriteMember(value, value.HorizontalSnapPointsType, "HorizontalSnapPointsType");
        }
        if (!ScrollViewer.VerticalSnapPointsTypeProperty.GetDefaultValue(typeof(ScrollViewer)).Equals(value.VerticalSnapPointsType))
        {
            writer.WriteMember(value, value.VerticalSnapPointsType, "VerticalSnapPointsType");
        }
        if (!ScrollViewer.HorizontalSnapPointsAlignmentProperty.GetDefaultValue(typeof(ScrollViewer)).Equals(value.HorizontalSnapPointsAlignment))
        {
            writer.WriteMember(value, value.HorizontalSnapPointsAlignment, "HorizontalSnapPointsAlignment");
        }
        if (!ScrollViewer.VerticalSnapPointsAlignmentProperty.GetDefaultValue(typeof(ScrollViewer)).Equals(value.VerticalSnapPointsAlignment))
        {
            writer.WriteMember(value, value.VerticalSnapPointsAlignment, "VerticalSnapPointsAlignment");
        }
        if (!ScrollViewer.AllowAutoHideProperty.GetDefaultValue(typeof(ScrollViewer)).Equals(value.AllowAutoHide))
        {
            writer.WriteMember(value, value.AllowAutoHide, "AllowAutoHide");
        }
        if (!ScrollViewer.IsScrollChainingEnabledProperty.GetDefaultValue(typeof(ScrollViewer)).Equals(value.IsScrollChainingEnabled))
        {
            writer.WriteMember(value, value.IsScrollChainingEnabled, "IsScrollChainingEnabled");
        }
        if (!ScrollViewer.IsScrollInertiaEnabledProperty.GetDefaultValue(typeof(ScrollViewer)).Equals(value.IsScrollInertiaEnabled))
        {
            writer.WriteMember(value, value.IsScrollInertiaEnabled, "IsScrollInertiaEnabled");
        }
    }
}
