// <auto-generated />
#nullable enable
class ScrollViewerConverter :
    WriteOnlyJsonConverter<ScrollViewer>
{
    public override void Write(VerifyJsonWriter writer, ScrollViewer value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ScrollViewer value)
    {
        var type = typeof(ScrollViewer);
        if (value.ShouldIncludeProperty(ScrollViewer.BringIntoViewOnFocusChangeProperty))
        if (!object.Equals(ScrollViewer.BringIntoViewOnFocusChangeProperty.GetDefaultValue(type), value.BringIntoViewOnFocusChange))
        {
            writer.WriteMember(value, value.BringIntoViewOnFocusChange, "BringIntoViewOnFocusChange");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.ExtentProperty))
        if (!object.Equals(ScrollViewer.ExtentProperty.GetUnsetValue(type), value.Extent))
        {
            writer.WriteMember(value, value.Extent, "Extent");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.OffsetProperty))
        if (!object.Equals(ScrollViewer.OffsetProperty.GetDefaultValue(type), value.Offset))
        {
            writer.WriteMember(value, value.Offset, "Offset");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.ViewportProperty))
        if (!object.Equals(ScrollViewer.ViewportProperty.GetUnsetValue(type), value.Viewport))
        {
            writer.WriteMember(value, value.Viewport, "Viewport");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.LargeChangeProperty))
        if (!object.Equals(ScrollViewer.LargeChangeProperty.GetUnsetValue(type), value.LargeChange))
        {
            writer.WriteMember(value, value.LargeChange, "LargeChange");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.SmallChangeProperty))
        if (!object.Equals(ScrollViewer.SmallChangeProperty.GetUnsetValue(type), value.SmallChange))
        {
            writer.WriteMember(value, value.SmallChange, "SmallChange");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.HorizontalScrollBarVisibilityProperty))
        if (!object.Equals(ScrollViewer.HorizontalScrollBarVisibilityProperty.GetDefaultValue(type), value.HorizontalScrollBarVisibility))
        {
            writer.WriteMember(value, value.HorizontalScrollBarVisibility, "HorizontalScrollBarVisibility");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.VerticalScrollBarVisibilityProperty))
        if (!object.Equals(ScrollViewer.VerticalScrollBarVisibilityProperty.GetDefaultValue(type), value.VerticalScrollBarVisibility))
        {
            writer.WriteMember(value, value.VerticalScrollBarVisibility, "VerticalScrollBarVisibility");
        }
        writer.WriteMember(value, value.CurrentAnchor, "CurrentAnchor");
        if (value.ShouldIncludeProperty(ScrollViewer.ScrollBarMaximumProperty))
        if (!object.Equals(ScrollViewer.ScrollBarMaximumProperty.GetUnsetValue(type), value.ScrollBarMaximum))
        {
            writer.WriteMember(value, value.ScrollBarMaximum, "ScrollBarMaximum");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.IsExpandedProperty))
        if (!object.Equals(ScrollViewer.IsExpandedProperty.GetUnsetValue(type), value.IsExpanded))
        {
            writer.WriteMember(value, value.IsExpanded, "IsExpanded");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.HorizontalSnapPointsTypeProperty))
        if (!object.Equals(ScrollViewer.HorizontalSnapPointsTypeProperty.GetDefaultValue(type), value.HorizontalSnapPointsType))
        {
            writer.WriteMember(value, value.HorizontalSnapPointsType, "HorizontalSnapPointsType");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.VerticalSnapPointsTypeProperty))
        if (!object.Equals(ScrollViewer.VerticalSnapPointsTypeProperty.GetDefaultValue(type), value.VerticalSnapPointsType))
        {
            writer.WriteMember(value, value.VerticalSnapPointsType, "VerticalSnapPointsType");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.HorizontalSnapPointsAlignmentProperty))
        if (!object.Equals(ScrollViewer.HorizontalSnapPointsAlignmentProperty.GetDefaultValue(type), value.HorizontalSnapPointsAlignment))
        {
            writer.WriteMember(value, value.HorizontalSnapPointsAlignment, "HorizontalSnapPointsAlignment");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.VerticalSnapPointsAlignmentProperty))
        if (!object.Equals(ScrollViewer.VerticalSnapPointsAlignmentProperty.GetDefaultValue(type), value.VerticalSnapPointsAlignment))
        {
            writer.WriteMember(value, value.VerticalSnapPointsAlignment, "VerticalSnapPointsAlignment");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.AllowAutoHideProperty))
        if (!object.Equals(ScrollViewer.AllowAutoHideProperty.GetDefaultValue(type), value.AllowAutoHide))
        {
            writer.WriteMember(value, value.AllowAutoHide, "AllowAutoHide");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.IsScrollChainingEnabledProperty))
        if (!object.Equals(ScrollViewer.IsScrollChainingEnabledProperty.GetDefaultValue(type), value.IsScrollChainingEnabled))
        {
            writer.WriteMember(value, value.IsScrollChainingEnabled, "IsScrollChainingEnabled");
        }
        if (value.ShouldIncludeProperty(ScrollViewer.IsScrollInertiaEnabledProperty))
        if (!object.Equals(ScrollViewer.IsScrollInertiaEnabledProperty.GetDefaultValue(type), value.IsScrollInertiaEnabled))
        {
            writer.WriteMember(value, value.IsScrollInertiaEnabled, "IsScrollInertiaEnabled");
        }
    }
}
