// <auto-generated />
class SelectingItemsControlConverter :
    WriteOnlyJsonConverter<SelectingItemsControl>
{
    public override void Write(VerifyJsonWriter writer, SelectingItemsControl value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ItemsControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, SelectingItemsControl value)
    {
        if (!object.Equals(SelectingItemsControl.AutoScrollToSelectedItemProperty.GetDefaultValue(typeof(SelectingItemsControl)), value.AutoScrollToSelectedItem))
        {
            writer.WriteMember(value, value.AutoScrollToSelectedItem, "AutoScrollToSelectedItem");
        }
        if (!object.Equals(SelectingItemsControl.SelectedIndexProperty.GetUnsetValue(typeof(SelectingItemsControl)), value.SelectedIndex))
        {
            writer.WriteMember(value, value.SelectedIndex, "SelectedIndex");
        }
        if (!object.Equals(SelectingItemsControl.SelectedItemProperty.GetUnsetValue(typeof(SelectingItemsControl)), value.SelectedItem))
        {
            writer.WriteMember(value, value.SelectedItem, "SelectedItem");
        }
        if (!object.Equals(SelectingItemsControl.SelectedValueBindingProperty.GetDefaultValue(typeof(SelectingItemsControl)), value.SelectedValueBinding))
        {
            writer.WriteMember(value, value.SelectedValueBinding, "SelectedValueBinding");
        }
        if (!object.Equals(SelectingItemsControl.SelectedValueProperty.GetDefaultValue(typeof(SelectingItemsControl)), value.SelectedValue))
        {
            writer.WriteMember(value, value.SelectedValue, "SelectedValue");
        }
        if (!object.Equals(SelectingItemsControl.IsTextSearchEnabledProperty.GetDefaultValue(typeof(SelectingItemsControl)), value.IsTextSearchEnabled))
        {
            writer.WriteMember(value, value.IsTextSearchEnabled, "IsTextSearchEnabled");
        }
        if (!object.Equals(SelectingItemsControl.WrapSelectionProperty.GetDefaultValue(typeof(SelectingItemsControl)), value.WrapSelection))
        {
            writer.WriteMember(value, value.WrapSelection, "WrapSelection");
        }
    }
}
