// <auto-generated />
#nullable enable
class SelectingItemsControlConverter :
    WriteOnlyJsonConverter<SelectingItemsControl>
{
    public override void Write(VerifyJsonWriter writer, SelectingItemsControl value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ItemsControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, SelectingItemsControl value)
    {
        var type = typeof(SelectingItemsControl);
        if (SelectingItemsControl.AutoScrollToSelectedItemProperty.ShouldIncludeProperty(value, value.AutoScrollToSelectedItem))
        {
            writer.WriteMember(value, value.AutoScrollToSelectedItem, "AutoScrollToSelectedItem");
        }
        if (SelectingItemsControl.SelectedIndexProperty.ShouldIncludeProperty(value, value.SelectedIndex))
        {
            writer.WriteMember(value, value.SelectedIndex, "SelectedIndex");
        }
        if (SelectingItemsControl.SelectedItemProperty.ShouldIncludeProperty(value, value.SelectedItem))
        {
            writer.WriteMember(value, value.SelectedItem, "SelectedItem");
        }
        if (SelectingItemsControl.SelectedValueBindingProperty.ShouldIncludeProperty(value, value.SelectedValueBinding))
        {
            writer.WriteMember(value, value.SelectedValueBinding, "SelectedValueBinding");
        }
        if (SelectingItemsControl.SelectedValueProperty.ShouldIncludeProperty(value, value.SelectedValue))
        {
            writer.WriteMember(value, value.SelectedValue, "SelectedValue");
        }
        if (SelectingItemsControl.IsTextSearchEnabledProperty.ShouldIncludeProperty(value, value.IsTextSearchEnabled))
        {
            writer.WriteMember(value, value.IsTextSearchEnabled, "IsTextSearchEnabled");
        }
        if (SelectingItemsControl.WrapSelectionProperty.ShouldIncludeProperty(value, value.WrapSelection))
        {
            writer.WriteMember(value, value.WrapSelection, "WrapSelection");
        }
    }
}
