// <auto-generated />
#nullable enable
class SeparatorConverter :
    WriteOnlyJsonConverter<Separator>
{
    public override void Write(VerifyJsonWriter writer, Separator value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TemplatedControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Separator value)
    {
    }

    public static bool MemberHasValue(Separator target, string member, object? value)
    {
        TemplatedControlConverter.MemberHasValue(target, member, value);
        throw new($"Member not found: {member}");
    }
}
