// <auto-generated />
#nullable enable
class SplitButtonConverter :
    WriteOnlyJsonConverter<SplitButton>
{
    public override void Write(VerifyJsonWriter writer, SplitButton value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, SplitButton value)
    {
        if (value.ShouldIncludeProperty(SplitButton.CommandProperty))
        if (!object.Equals(SplitButton.CommandProperty.GetDefaultValue(typeof(SplitButton)), value.Command))
        {
            writer.WriteMember(value, value.Command, "Command");
        }
        if (value.ShouldIncludeProperty(SplitButton.CommandParameterProperty))
        if (!object.Equals(SplitButton.CommandParameterProperty.GetDefaultValue(typeof(SplitButton)), value.CommandParameter))
        {
            writer.WriteMember(value, value.CommandParameter, "CommandParameter");
        }
        if (value.ShouldIncludeProperty(SplitButton.FlyoutProperty))
        if (!object.Equals(SplitButton.FlyoutProperty.GetDefaultValue(typeof(SplitButton)), value.Flyout))
        {
            writer.WriteMember(value, value.Flyout, "Flyout");
        }
    }
}
