// <auto-generated />
#nullable enable
class SplitButtonConverter :
    WriteOnlyJsonConverter<SplitButton>
{
    public override void Write(VerifyJsonWriter writer, SplitButton value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, SplitButton value)
    {
        if (!object.Equals(SplitButton.CommandProperty.GetDefaultValue(typeof(SplitButton)), value.Command))
        {
            writer.WriteMember(value, value.Command, "Command");
        }
        if (!object.Equals(SplitButton.CommandParameterProperty.GetDefaultValue(typeof(SplitButton)), value.CommandParameter))
        {
            writer.WriteMember(value, value.CommandParameter, "CommandParameter");
        }
        if (!object.Equals(SplitButton.FlyoutProperty.GetDefaultValue(typeof(SplitButton)), value.Flyout))
        {
            writer.WriteMember(value, value.Flyout, "Flyout");
        }
    }

    public static bool MemberHasValue(SplitButton target, string member, object? value)
    {
        if (member == "Command")
        {
            return object.Equals(target.Command, value);
        }
        if (member == "CommandParameter")
        {
            return object.Equals(target.CommandParameter, value);
        }
        if (member == "Flyout")
        {
            return object.Equals(target.Flyout, value);
        }
        ContentControlConverter.MemberHasValue(target, member, value);
        throw new($"Member not found: {member}");
    }
}
