// <auto-generated />
class StackPanelConverter :
    WriteOnlyJsonConverter<StackPanel>
{
    public override void Write(VerifyJsonWriter writer, StackPanel value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, StackPanel value)
    {
        if (!object.Equals(StackPanel.SpacingProperty.GetDefaultValue(typeof(StackPanel)), value.Spacing))
        {
            writer.WriteMember(value, value.Spacing, "Spacing");
        }
        if (!object.Equals(StackPanel.OrientationProperty.GetDefaultValue(typeof(StackPanel)), value.Orientation))
        {
            writer.WriteMember(value, value.Orientation, "Orientation");
        }
        if (!object.Equals(StackPanel.AreHorizontalSnapPointsRegularProperty.GetDefaultValue(typeof(StackPanel)), value.AreHorizontalSnapPointsRegular))
        {
            writer.WriteMember(value, value.AreHorizontalSnapPointsRegular, "AreHorizontalSnapPointsRegular");
        }
        if (!object.Equals(StackPanel.AreVerticalSnapPointsRegularProperty.GetDefaultValue(typeof(StackPanel)), value.AreVerticalSnapPointsRegular))
        {
            writer.WriteMember(value, value.AreVerticalSnapPointsRegular, "AreVerticalSnapPointsRegular");
        }
    }
}
