// <auto-generated />
class StackPanelConverter :
    WriteOnlyJsonConverter<StackPanel>
{
    public override void Write(VerifyJsonWriter writer, StackPanel value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, StackPanel value)
    {
         if (!StackPanel.SpacingProperty.GetDefaultValue(typeof(StackPanel)).Equals(value.Spacing))
         {
             writer.WriteMember(value, value.Spacing, "Spacing");
         }
         if (!StackPanel.OrientationProperty.GetDefaultValue(typeof(StackPanel)).Equals(value.Orientation))
         {
             writer.WriteMember(value, value.Orientation, "Orientation");
         }
         if (!StackPanel.AreHorizontalSnapPointsRegularProperty.GetDefaultValue(typeof(StackPanel)).Equals(value.AreHorizontalSnapPointsRegular))
         {
             writer.WriteMember(value, value.AreHorizontalSnapPointsRegular, "AreHorizontalSnapPointsRegular");
         }
         if (!StackPanel.AreVerticalSnapPointsRegularProperty.GetDefaultValue(typeof(StackPanel)).Equals(value.AreVerticalSnapPointsRegular))
         {
             writer.WriteMember(value, value.AreVerticalSnapPointsRegular, "AreVerticalSnapPointsRegular");
         }
    }
}
