// <auto-generated />
#nullable enable
class TabItemConverter :
    WriteOnlyJsonConverter<TabItem>
{
    public override void Write(VerifyJsonWriter writer, TabItem value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        HeaderedContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, TabItem value)
    {
        if (value.ShouldIncludeProperty(TabItem.TabStripPlacementProperty))
        if (!object.Equals(TabItem.TabStripPlacementProperty.GetUnsetValue(typeof(TabItem)), value.TabStripPlacement))
        {
            writer.WriteMember(value, value.TabStripPlacement, "TabStripPlacement");
        }
        if (value.ShouldIncludeProperty(TabItem.IsSelectedProperty))
        if (!object.Equals(TabItem.IsSelectedProperty.GetDefaultValue(typeof(TabItem)), value.IsSelected))
        {
            writer.WriteMember(value, value.IsSelected, "IsSelected");
        }
    }
}
