// <auto-generated />
class TabItemConverter :
    WriteOnlyJsonConverter<TabItem>
{
    public override void Write(VerifyJsonWriter writer, TabItem value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        HeaderedContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, TabItem value)
    {
        if (!TabItem.TabStripPlacementProperty.GetUnsetValue(typeof(TabItem)).Equals(value.TabStripPlacement))
        {
            writer.WriteMember(value, value.TabStripPlacement, "TabStripPlacement");
        }
        if (!TabItem.IsSelectedProperty.GetDefaultValue(typeof(TabItem)).Equals(value.IsSelected))
        {
            writer.WriteMember(value, value.IsSelected, "IsSelected");
        }
    }
}
