// <auto-generated />
#nullable enable
class TemplatedControlConverter :
    WriteOnlyJsonConverter<TemplatedControl>
{
    public override void Write(VerifyJsonWriter writer, TemplatedControl value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, TemplatedControl value)
    {
        if (TemplatedControl.BackgroundProperty.ShouldIncludeProperty(value, value.Background))
        {
            writer.WriteMember(value, value.Background, "Background");
        }
        if (TemplatedControl.BorderBrushProperty.ShouldIncludeProperty(value, value.BorderBrush))
        {
            writer.WriteMember(value, value.BorderBrush, "BorderBrush");
        }
        if (TemplatedControl.BorderThicknessProperty.ShouldIncludeProperty(value, value.BorderThickness))
        {
            writer.WriteMember(value, value.BorderThickness, "BorderThickness");
        }
        if (TemplatedControl.CornerRadiusProperty.ShouldIncludeProperty(value, value.CornerRadius))
        {
            writer.WriteMember(value, value.CornerRadius, "CornerRadius");
        }
        if (TemplatedControl.FontFamilyProperty.ShouldIncludeProperty(value, value.FontFamily))
        {
            writer.WriteMember(value, value.FontFamily, "FontFamily");
        }
        if (TemplatedControl.FontSizeProperty.ShouldIncludeProperty(value, value.FontSize))
        {
            writer.WriteMember(value, value.FontSize, "FontSize");
        }
        if (TemplatedControl.FontStyleProperty.ShouldIncludeProperty(value, value.FontStyle))
        {
            writer.WriteMember(value, value.FontStyle, "FontStyle");
        }
        if (TemplatedControl.FontWeightProperty.ShouldIncludeProperty(value, value.FontWeight))
        {
            writer.WriteMember(value, value.FontWeight, "FontWeight");
        }
        if (TemplatedControl.FontStretchProperty.ShouldIncludeProperty(value, value.FontStretch))
        {
            writer.WriteMember(value, value.FontStretch, "FontStretch");
        }
        if (TemplatedControl.ForegroundProperty.ShouldIncludeProperty(value, value.Foreground))
        {
            writer.WriteMember(value, value.Foreground, "Foreground");
        }
        if (TemplatedControl.PaddingProperty.ShouldIncludeProperty(value, value.Padding))
        {
            writer.WriteMember(value, value.Padding, "Padding");
        }
    }
}
