// <auto-generated />
class TimePickerPresenterConverter :
    WriteOnlyJsonConverter<TimePickerPresenter>
{
    public override void Write(VerifyJsonWriter writer, TimePickerPresenter value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PickerPresenterBaseConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, TimePickerPresenter value)
    {
         if (!TimePickerPresenter.MinuteIncrementProperty.GetDefaultValue(typeof(TimePickerPresenter)).Equals(value.MinuteIncrement))
         {
             writer.WriteMember(value, value.MinuteIncrement, "MinuteIncrement");
         }
         if (TimePickerPresenter.ClockIdentifierProperty.GetDefaultValue(typeof(TimePickerPresenter)) != value.ClockIdentifier)
         {
             writer.WriteMember(value, value.ClockIdentifier, "ClockIdentifier");
         }
         if (!TimePickerPresenter.TimeProperty.GetDefaultValue(typeof(TimePickerPresenter)).Equals(value.Time))
         {
             writer.WriteMember(value, value.Time, "Time");
         }
    }
}
