// <auto-generated />
#nullable enable
class TimePickerConverter :
    WriteOnlyJsonConverter<TimePicker>
{
    public override void Write(VerifyJsonWriter writer, TimePicker value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TemplatedControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, TimePicker value)
    {
        var type = typeof(TimePicker);
        if (value.ShouldIncludeProperty(TimePicker.MinuteIncrementProperty))
        if (!object.Equals(TimePicker.MinuteIncrementProperty.GetDefaultValue(type), value.MinuteIncrement))
        {
            writer.WriteMember(value, value.MinuteIncrement, "MinuteIncrement");
        }
        if (value.ShouldIncludeProperty(TimePicker.ClockIdentifierProperty))
        if (!object.Equals(TimePicker.ClockIdentifierProperty.GetDefaultValue(type), value.ClockIdentifier))
        {
            writer.WriteMember(value, value.ClockIdentifier, "ClockIdentifier");
        }
        if (value.ShouldIncludeProperty(TimePicker.SelectedTimeProperty))
        if (!object.Equals(TimePicker.SelectedTimeProperty.GetDefaultValue(type), value.SelectedTime))
        {
            writer.WriteMember(value, value.SelectedTime, "SelectedTime");
        }
    }
}
