// <auto-generated />
#nullable enable
class TopLevelConverter :
    WriteOnlyJsonConverter<TopLevel>
{
    public override void Write(VerifyJsonWriter writer, TopLevel value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, TopLevel value)
    {
        if (value.ShouldIncludeProperty(TopLevel.ClientSizeProperty))
        if (!object.Equals(TopLevel.ClientSizeProperty.GetUnsetValue(typeof(TopLevel)), value.ClientSize))
        {
            writer.WriteMember(value, value.ClientSize, "ClientSize");
        }
        if (value.ShouldIncludeProperty(TopLevel.FrameSizeProperty))
        if (!object.Equals(TopLevel.FrameSizeProperty.GetUnsetValue(typeof(TopLevel)), value.FrameSize))
        {
            writer.WriteMember(value, value.FrameSize, "FrameSize");
        }
        if (value.ShouldIncludeProperty(TopLevel.TransparencyLevelHintProperty))
        if (!object.Equals(TopLevel.TransparencyLevelHintProperty.GetDefaultValue(typeof(TopLevel)), value.TransparencyLevelHint))
        {
            writer.WriteMember(value, value.TransparencyLevelHint, "TransparencyLevelHint");
        }
        if (value.ShouldIncludeProperty(TopLevel.ActualTransparencyLevelProperty))
        if (!object.Equals(TopLevel.ActualTransparencyLevelProperty.GetUnsetValue(typeof(TopLevel)), value.ActualTransparencyLevel))
        {
            writer.WriteMember(value, value.ActualTransparencyLevel, "ActualTransparencyLevel");
        }
        if (value.ShouldIncludeProperty(TopLevel.TransparencyBackgroundFallbackProperty))
        if (!object.Equals(TopLevel.TransparencyBackgroundFallbackProperty.GetDefaultValue(typeof(TopLevel)), value.TransparencyBackgroundFallback))
        {
            writer.WriteMember(value, value.TransparencyBackgroundFallback, "TransparencyBackgroundFallback");
        }
        if (value.ShouldIncludeProperty(TopLevel.RequestedThemeVariantProperty))
        if (!object.Equals(TopLevel.RequestedThemeVariantProperty.GetDefaultValue(typeof(TopLevel)), value.RequestedThemeVariant))
        {
            writer.WriteMember(value, value.RequestedThemeVariant, "RequestedThemeVariant");
        }
        writer.WriteMember(value, value.PlatformImpl, "PlatformImpl");
        writer.WriteMember(value, value.RendererDiagnostics, "RendererDiagnostics");
        writer.WriteMember(value, value.RenderScaling, "RenderScaling");
        writer.WriteMember(value, value.StorageProvider, "StorageProvider");
        writer.WriteMember(value, value.InsetsManager, "InsetsManager");
        writer.WriteMember(value, value.Clipboard, "Clipboard");
        writer.WriteMember(value, value.FocusManager, "FocusManager");
        writer.WriteMember(value, value.PlatformSettings, "PlatformSettings");
    }
}
