// <auto-generated />
class TreeViewConverter :
    WriteOnlyJsonConverter<TreeView>
{
    public override void Write(VerifyJsonWriter writer, TreeView value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ItemsControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, TreeView value)
    {
         writer.WriteMember(value, value.ItemContainerGenerator, "ItemContainerGenerator");
         if (!TreeView.AutoScrollToSelectedItemProperty.GetDefaultValue(typeof(TreeView)).Equals(value.AutoScrollToSelectedItem))
         {
             writer.WriteMember(value, value.AutoScrollToSelectedItem, "AutoScrollToSelectedItem");
         }
         if (!TreeView.SelectionModeProperty.GetDefaultValue(typeof(TreeView)).Equals(value.SelectionMode))
         {
             writer.WriteMember(value, value.SelectionMode, "SelectionMode");
         }
        if (TreeView.SelectedItemProperty.GetUnsetValue(typeof(TreeView)) != value.SelectedItem)
        {
            writer.WriteMember(value, value.SelectedItem, "SelectedItem");
        }
        if (TreeView.SelectedItemsProperty.GetUnsetValue(typeof(TreeView)) != value.SelectedItems)
        {
            writer.WriteMember(value, value.SelectedItems, "SelectedItems");
        }
    }
}
