// <auto-generated />
#nullable enable
class TreeViewItemConverter :
    WriteOnlyJsonConverter<TreeViewItem>
{
    public override void Write(VerifyJsonWriter writer, TreeViewItem value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        HeaderedItemsControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, TreeViewItem value)
    {
        var type = typeof(TreeViewItem);
        if (TreeViewItem.IsExpandedProperty.ShouldIncludeProperty(value, value.IsExpanded))
        {
            writer.WriteMember(value, value.IsExpanded, "IsExpanded");
        }
        if (TreeViewItem.IsSelectedProperty.ShouldIncludeProperty(value, value.IsSelected))
        {
            writer.WriteMember(value, value.IsSelected, "IsSelected");
        }
        if (TreeViewItem.LevelProperty.ShouldIncludeProperty(value, value.Level))
        {
            writer.WriteMember(value, value.Level, "Level");
        }
    }
}
