// <auto-generated />
#nullable enable
class TreeViewItemConverter :
    WriteOnlyJsonConverter<TreeViewItem>
{
    public override void Write(VerifyJsonWriter writer, TreeViewItem value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        HeaderedItemsControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, TreeViewItem value)
    {
        var type = typeof(TreeViewItem);
        if (value.ShouldIncludeProperty(TreeViewItem.IsExpandedProperty))
        if (!object.Equals(TreeViewItem.IsExpandedProperty.GetDefaultValue(type), value.IsExpanded))
        {
            writer.WriteMember(value, value.IsExpanded, "IsExpanded");
        }
        if (value.ShouldIncludeProperty(TreeViewItem.IsSelectedProperty))
        if (!object.Equals(TreeViewItem.IsSelectedProperty.GetDefaultValue(type), value.IsSelected))
        {
            writer.WriteMember(value, value.IsSelected, "IsSelected");
        }
        if (value.ShouldIncludeProperty(TreeViewItem.LevelProperty))
        if (!object.Equals(TreeViewItem.LevelProperty.GetUnsetValue(type), value.Level))
        {
            writer.WriteMember(value, value.Level, "Level");
        }
    }
}
