// <auto-generated />
#nullable enable
class UniformGridConverter :
    WriteOnlyJsonConverter<UniformGrid>
{
    public override void Write(VerifyJsonWriter writer, UniformGrid value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, UniformGrid value)
    {
        if (value.ShouldIncludeProperty(UniformGrid.RowsProperty))
        if (!object.Equals(UniformGrid.RowsProperty.GetDefaultValue(typeof(UniformGrid)), value.Rows))
        {
            writer.WriteMember(value, value.Rows, "Rows");
        }
        if (value.ShouldIncludeProperty(UniformGrid.ColumnsProperty))
        if (!object.Equals(UniformGrid.ColumnsProperty.GetDefaultValue(typeof(UniformGrid)), value.Columns))
        {
            writer.WriteMember(value, value.Columns, "Columns");
        }
        if (value.ShouldIncludeProperty(UniformGrid.FirstColumnProperty))
        if (!object.Equals(UniformGrid.FirstColumnProperty.GetDefaultValue(typeof(UniformGrid)), value.FirstColumn))
        {
            writer.WriteMember(value, value.FirstColumn, "FirstColumn");
        }
    }
}
