// <auto-generated />
#nullable enable
class UniformGridConverter :
    WriteOnlyJsonConverter<UniformGrid>
{
    public override void Write(VerifyJsonWriter writer, UniformGrid value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, UniformGrid value)
    {
        var type = typeof(UniformGrid);
        if (UniformGrid.RowsProperty.ShouldIncludeProperty(value, value.Rows))
        {
            writer.WriteMember(value, value.Rows, "Rows");
        }
        if (UniformGrid.ColumnsProperty.ShouldIncludeProperty(value, value.Columns))
        {
            writer.WriteMember(value, value.Columns, "Columns");
        }
        if (UniformGrid.FirstColumnProperty.ShouldIncludeProperty(value, value.FirstColumn))
        {
            writer.WriteMember(value, value.FirstColumn, "FirstColumn");
        }
    }
}
