// <auto-generated />
class UniformGridConverter :
    WriteOnlyJsonConverter<UniformGrid>
{
    public override void Write(VerifyJsonWriter writer, UniformGrid value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, UniformGrid value)
    {
         if (!UniformGrid.RowsProperty.GetDefaultValue(typeof(UniformGrid)).Equals(value.Rows))
         {
             writer.WriteMember(value, value.Rows, "Rows");
         }
         if (!UniformGrid.ColumnsProperty.GetDefaultValue(typeof(UniformGrid)).Equals(value.Columns))
         {
             writer.WriteMember(value, value.Columns, "Columns");
         }
         if (!UniformGrid.FirstColumnProperty.GetDefaultValue(typeof(UniformGrid)).Equals(value.FirstColumn))
         {
             writer.WriteMember(value, value.FirstColumn, "FirstColumn");
         }
    }
}
