// <auto-generated />
#nullable enable
class ViewboxConverter :
    WriteOnlyJsonConverter<Viewbox>
{
    public override void Write(VerifyJsonWriter writer, Viewbox value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Viewbox value)
    {
        var type = typeof(Viewbox);
        if (value.ShouldIncludeProperty(Viewbox.StretchProperty))
        if (!object.Equals(Viewbox.StretchProperty.GetDefaultValue(type), value.Stretch))
        {
            writer.WriteMember(value, value.Stretch, "Stretch");
        }
        if (value.ShouldIncludeProperty(Viewbox.StretchDirectionProperty))
        if (!object.Equals(Viewbox.StretchDirectionProperty.GetDefaultValue(type), value.StretchDirection))
        {
            writer.WriteMember(value, value.StretchDirection, "StretchDirection");
        }
        if (value.ShouldIncludeProperty(Viewbox.ChildProperty))
        if (!object.Equals(Viewbox.ChildProperty.GetDefaultValue(type), value.Child))
        {
            writer.WriteMember(value, value.Child, "Child");
        }
    }
}
