// <auto-generated />
#nullable enable
class VirtualizingCarouselPanelConverter :
    WriteOnlyJsonConverter<VirtualizingCarouselPanel>
{
    public override void Write(VerifyJsonWriter writer, VirtualizingCarouselPanel value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        VirtualizingPanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, VirtualizingCarouselPanel value)
    {
    }
}
