// <auto-generated />
#nullable enable
class VirtualizingStackPanelConverter :
    WriteOnlyJsonConverter<VirtualizingStackPanel>
{
    public override void Write(VerifyJsonWriter writer, VirtualizingStackPanel value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        VirtualizingPanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, VirtualizingStackPanel value)
    {
        var type = typeof(VirtualizingStackPanel);
        if (VirtualizingStackPanel.OrientationProperty.ShouldIncludeProperty(value, value.Orientation))
        {
            writer.WriteMember(value, value.Orientation, "Orientation");
        }
        if (VirtualizingStackPanel.AreHorizontalSnapPointsRegularProperty.ShouldIncludeProperty(value, value.AreHorizontalSnapPointsRegular))
        {
            writer.WriteMember(value, value.AreHorizontalSnapPointsRegular, "AreHorizontalSnapPointsRegular");
        }
        if (VirtualizingStackPanel.AreVerticalSnapPointsRegularProperty.ShouldIncludeProperty(value, value.AreVerticalSnapPointsRegular))
        {
            writer.WriteMember(value, value.AreVerticalSnapPointsRegular, "AreVerticalSnapPointsRegular");
        }
        writer.WriteMember(value, value.FirstRealizedIndex, "FirstRealizedIndex");
        writer.WriteMember(value, value.LastRealizedIndex, "LastRealizedIndex");
    }
}
