// <auto-generated />
#nullable enable
class WrapPanelConverter :
    WriteOnlyJsonConverter<WrapPanel>
{
    public override void Write(VerifyJsonWriter writer, WrapPanel value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, WrapPanel value)
    {
        var type = typeof(WrapPanel);
        if (value.ShouldIncludeProperty(WrapPanel.OrientationProperty))
        if (!object.Equals(WrapPanel.OrientationProperty.GetDefaultValue(type), value.Orientation))
        {
            writer.WriteMember(value, value.Orientation, "Orientation");
        }
        if (value.ShouldIncludeProperty(WrapPanel.ItemWidthProperty))
        if (!object.Equals(WrapPanel.ItemWidthProperty.GetDefaultValue(type), value.ItemWidth))
        {
            writer.WriteMember(value, value.ItemWidth, "ItemWidth");
        }
        if (value.ShouldIncludeProperty(WrapPanel.ItemHeightProperty))
        if (!object.Equals(WrapPanel.ItemHeightProperty.GetDefaultValue(type), value.ItemHeight))
        {
            writer.WriteMember(value, value.ItemHeight, "ItemHeight");
        }
    }
}
