// <auto-generated />
class WrapPanelConverter :
    WriteOnlyJsonConverter<WrapPanel>
{
    public override void Write(VerifyJsonWriter writer, WrapPanel value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, WrapPanel value)
    {
         if (WrapPanel.OrientationProperty.GetDefaultValue(typeof(WrapPanel)) != value.Orientation)
         {
             writer.WriteMember(value, value.Orientation, "Orientation");
         }
         if (WrapPanel.ItemWidthProperty.GetDefaultValue(typeof(WrapPanel)) != value.ItemWidth)
         {
             writer.WriteMember(value, value.ItemWidth, "ItemWidth");
         }
         if (WrapPanel.ItemHeightProperty.GetDefaultValue(typeof(WrapPanel)) != value.ItemHeight)
         {
             writer.WriteMember(value, value.ItemHeight, "ItemHeight");
         }
    }
}
