global using System.Globalization;
global using Argon;
global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Data;
global using Avalonia.Diagnostics;
global using Avalonia.Headless;
global using Avalonia.Input;
global using Avalonia.Media;