// <auto-generated />
class DockPanelConverter :
    WriteOnlyJsonConverter<DockPanel>
{
    public override void Write(VerifyJsonWriter writer, DockPanel value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        PanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, DockPanel value)
    {
         if (DockPanel.LastChildFillProperty.GetDefaultValue(typeof(DockPanel)) == value.LastChildFill)
         {
             writer.WriteMember(value, value.LastChildFill, "LastChildFill");
         }
    }
}
