// <auto-generated />
class HeaderedSelectingItemsControlConverter :
    WriteOnlyJsonConverter<HeaderedSelectingItemsControl>
{
    public override void Write(VerifyJsonWriter writer, HeaderedSelectingItemsControl value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        SelectingItemsControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, HeaderedSelectingItemsControl value)
    {
         if (HeaderedSelectingItemsControl.HeaderProperty.GetDefaultValue(typeof(HeaderedSelectingItemsControl)) != value.Header)
         {
             writer.WriteMember(value, value.Header, "Header");
         }
         if (HeaderedSelectingItemsControl.HeaderTemplateProperty.GetDefaultValue(typeof(HeaderedSelectingItemsControl)) != value.HeaderTemplate)
         {
             writer.WriteMember(value, value.HeaderTemplate, "HeaderTemplate");
         }
         writer.WriteMember(value, value.HeaderPresenter, "HeaderPresenter");
    }
}
