// <auto-generated />
class InteractiveConverter :
    WriteOnlyJsonConverter<Interactive>
{
    public override void Write(VerifyJsonWriter writer, Interactive value)
    {
        writer.WriteStartObject();
        WriteMembers(writer, value);
        LayoutableConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Interactive value)
    {
    }
}
