// <auto-generated />
class ItemsControlConverter :
    WriteOnlyJsonConverter<ItemsControl>
{
    public override void Write(VerifyJsonWriter writer, ItemsControl value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        TemplatedControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, ItemsControl value)
    {
         writer.WriteMember(value, value.DisplayMemberBinding, "DisplayMemberBinding");
         writer.WriteMember(value, value.ItemContainerGenerator, "ItemContainerGenerator");
         writer.WriteMember(value, value.Items, "Items");
         writer.WriteMember(value, value.ItemContainerTheme, "ItemContainerTheme");
         writer.WriteMember(value, value.ItemCount, "ItemCount");
         writer.WriteMember(value, value.ItemsPanel, "ItemsPanel");
         writer.WriteMember(value, value.ItemsSource, "ItemsSource");
         writer.WriteMember(value, value.ItemTemplate, "ItemTemplate");
         writer.WriteMember(value, value.Presenter, "Presenter");
         writer.WriteMember(value, value.ItemsPanelRoot, "ItemsPanelRoot");
         writer.WriteMember(value, value.ItemsView, "ItemsView");
    }
}
