// <auto-generated />
class NotificationCardConverter :
    WriteOnlyJsonConverter<NotificationCard>
{
    public override void Write(VerifyJsonWriter writer, NotificationCard value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, NotificationCard value)
    {
         if (NotificationCard.IsClosingProperty.GetUnsetValue(typeof(NotificationCard)) == value.IsClosing)
         {
             writer.WriteMember(value, value.IsClosing, "IsClosing");
         }
         if (NotificationCard.IsClosedProperty.GetDefaultValue(typeof(NotificationCard)) == value.IsClosed)
         {
             writer.WriteMember(value, value.IsClosed, "IsClosed");
         }
    }
}
