// <auto-generated />
class PolygonConverter :
    WriteOnlyJsonConverter<Polygon>
{
    public override void Write(VerifyJsonWriter writer, Polygon value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ShapeConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, Polygon value)
    {
         if (Polygon.PointsProperty.GetDefaultValue(typeof(Polygon)) == value.Points)
         {
             writer.WriteMember(value, value.Points, "Points");
         }
    }
}
