// <auto-generated />
class TabStripConverter :
    WriteOnlyJsonConverter<TabStrip>
{
    public override void Write(VerifyJsonWriter writer, TabStrip value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        SelectingItemsControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, TabStrip value)
    {
    }
}
