// <auto-generated />
class TransitioningContentControlConverter :
    WriteOnlyJsonConverter<TransitioningContentControl>
{
    public override void Write(VerifyJsonWriter writer, TransitioningContentControl value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        ContentControlConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, TransitioningContentControl value)
    {
         if (TransitioningContentControl.PageTransitionProperty.GetDefaultValue(typeof(TransitioningContentControl)) != value.PageTransition)
         {
             writer.WriteMember(value, value.PageTransition, "PageTransition");
         }
    }
}
