// <auto-generated />
class VirtualizingStackPanelConverter :
    WriteOnlyJsonConverter<VirtualizingStackPanel>
{
    public override void Write(VerifyJsonWriter writer, VirtualizingStackPanel value)
    {
        writer.WriteStartObject();
        VerifyAvalonia.WriteGeneratedMembers(writer, value);
        WriteMembers(writer, value);
        VirtualizingPanelConverter.WriteMembers(writer, value);
        writer.WriteEndObject();
    }

    public static void WriteMembers(VerifyJsonWriter writer, VirtualizingStackPanel value)
    {
         writer.WriteMember(value, value.Orientation, "Orientation");
         writer.WriteMember(value, value.AreHorizontalSnapPointsRegular, "AreHorizontalSnapPointsRegular");
         writer.WriteMember(value, value.AreVerticalSnapPointsRegular, "AreVerticalSnapPointsRegular");
         writer.WriteMember(value, value.FirstRealizedIndex, "FirstRealizedIndex");
         writer.WriteMember(value, value.LastRealizedIndex, "LastRealizedIndex");
    }
}
